
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ApiKeyUsage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ApiKeyUsage
 * 
 */
export type ApiKeyUsageModel = runtime.Types.Result.DefaultSelection<Prisma.$ApiKeyUsagePayload>

export type AggregateApiKeyUsage = {
  _count: ApiKeyUsageCountAggregateOutputType | null
  _avg: ApiKeyUsageAvgAggregateOutputType | null
  _sum: ApiKeyUsageSumAggregateOutputType | null
  _min: ApiKeyUsageMinAggregateOutputType | null
  _max: ApiKeyUsageMaxAggregateOutputType | null
}

export type ApiKeyUsageAvgAggregateOutputType = {
  status: number | null
}

export type ApiKeyUsageSumAggregateOutputType = {
  status: number | null
}

export type ApiKeyUsageMinAggregateOutputType = {
  id: string | null
  apiKeyId: string | null
  endpoint: string | null
  method: string | null
  status: number | null
  timestamp: Date | null
  ipAddress: string | null
}

export type ApiKeyUsageMaxAggregateOutputType = {
  id: string | null
  apiKeyId: string | null
  endpoint: string | null
  method: string | null
  status: number | null
  timestamp: Date | null
  ipAddress: string | null
}

export type ApiKeyUsageCountAggregateOutputType = {
  id: number
  apiKeyId: number
  endpoint: number
  method: number
  status: number
  timestamp: number
  ipAddress: number
  _all: number
}


export type ApiKeyUsageAvgAggregateInputType = {
  status?: true
}

export type ApiKeyUsageSumAggregateInputType = {
  status?: true
}

export type ApiKeyUsageMinAggregateInputType = {
  id?: true
  apiKeyId?: true
  endpoint?: true
  method?: true
  status?: true
  timestamp?: true
  ipAddress?: true
}

export type ApiKeyUsageMaxAggregateInputType = {
  id?: true
  apiKeyId?: true
  endpoint?: true
  method?: true
  status?: true
  timestamp?: true
  ipAddress?: true
}

export type ApiKeyUsageCountAggregateInputType = {
  id?: true
  apiKeyId?: true
  endpoint?: true
  method?: true
  status?: true
  timestamp?: true
  ipAddress?: true
  _all?: true
}

export type ApiKeyUsageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApiKeyUsage to aggregate.
   */
  where?: Prisma.ApiKeyUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApiKeyUsages to fetch.
   */
  orderBy?: Prisma.ApiKeyUsageOrderByWithRelationInput | Prisma.ApiKeyUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApiKeyUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApiKeyUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApiKeyUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ApiKeyUsages
  **/
  _count?: true | ApiKeyUsageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ApiKeyUsageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ApiKeyUsageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApiKeyUsageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApiKeyUsageMaxAggregateInputType
}

export type GetApiKeyUsageAggregateType<T extends ApiKeyUsageAggregateArgs> = {
      [P in keyof T & keyof AggregateApiKeyUsage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApiKeyUsage[P]>
    : Prisma.GetScalarType<T[P], AggregateApiKeyUsage[P]>
}




export type ApiKeyUsageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApiKeyUsageWhereInput
  orderBy?: Prisma.ApiKeyUsageOrderByWithAggregationInput | Prisma.ApiKeyUsageOrderByWithAggregationInput[]
  by: Prisma.ApiKeyUsageScalarFieldEnum[] | Prisma.ApiKeyUsageScalarFieldEnum
  having?: Prisma.ApiKeyUsageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApiKeyUsageCountAggregateInputType | true
  _avg?: ApiKeyUsageAvgAggregateInputType
  _sum?: ApiKeyUsageSumAggregateInputType
  _min?: ApiKeyUsageMinAggregateInputType
  _max?: ApiKeyUsageMaxAggregateInputType
}

export type ApiKeyUsageGroupByOutputType = {
  id: string
  apiKeyId: string
  endpoint: string
  method: string
  status: number
  timestamp: Date
  ipAddress: string | null
  _count: ApiKeyUsageCountAggregateOutputType | null
  _avg: ApiKeyUsageAvgAggregateOutputType | null
  _sum: ApiKeyUsageSumAggregateOutputType | null
  _min: ApiKeyUsageMinAggregateOutputType | null
  _max: ApiKeyUsageMaxAggregateOutputType | null
}

type GetApiKeyUsageGroupByPayload<T extends ApiKeyUsageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApiKeyUsageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApiKeyUsageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApiKeyUsageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApiKeyUsageGroupByOutputType[P]>
      }
    >
  >



export type ApiKeyUsageWhereInput = {
  AND?: Prisma.ApiKeyUsageWhereInput | Prisma.ApiKeyUsageWhereInput[]
  OR?: Prisma.ApiKeyUsageWhereInput[]
  NOT?: Prisma.ApiKeyUsageWhereInput | Prisma.ApiKeyUsageWhereInput[]
  id?: Prisma.StringFilter<"ApiKeyUsage"> | string
  apiKeyId?: Prisma.StringFilter<"ApiKeyUsage"> | string
  endpoint?: Prisma.StringFilter<"ApiKeyUsage"> | string
  method?: Prisma.StringFilter<"ApiKeyUsage"> | string
  status?: Prisma.IntFilter<"ApiKeyUsage"> | number
  timestamp?: Prisma.DateTimeFilter<"ApiKeyUsage"> | Date | string
  ipAddress?: Prisma.StringNullableFilter<"ApiKeyUsage"> | string | null
}

export type ApiKeyUsageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  apiKeyId?: Prisma.SortOrder
  endpoint?: Prisma.SortOrder
  method?: Prisma.SortOrder
  status?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type ApiKeyUsageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ApiKeyUsageWhereInput | Prisma.ApiKeyUsageWhereInput[]
  OR?: Prisma.ApiKeyUsageWhereInput[]
  NOT?: Prisma.ApiKeyUsageWhereInput | Prisma.ApiKeyUsageWhereInput[]
  apiKeyId?: Prisma.StringFilter<"ApiKeyUsage"> | string
  endpoint?: Prisma.StringFilter<"ApiKeyUsage"> | string
  method?: Prisma.StringFilter<"ApiKeyUsage"> | string
  status?: Prisma.IntFilter<"ApiKeyUsage"> | number
  timestamp?: Prisma.DateTimeFilter<"ApiKeyUsage"> | Date | string
  ipAddress?: Prisma.StringNullableFilter<"ApiKeyUsage"> | string | null
}, "id">

export type ApiKeyUsageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  apiKeyId?: Prisma.SortOrder
  endpoint?: Prisma.SortOrder
  method?: Prisma.SortOrder
  status?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ApiKeyUsageCountOrderByAggregateInput
  _avg?: Prisma.ApiKeyUsageAvgOrderByAggregateInput
  _max?: Prisma.ApiKeyUsageMaxOrderByAggregateInput
  _min?: Prisma.ApiKeyUsageMinOrderByAggregateInput
  _sum?: Prisma.ApiKeyUsageSumOrderByAggregateInput
}

export type ApiKeyUsageScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApiKeyUsageScalarWhereWithAggregatesInput | Prisma.ApiKeyUsageScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApiKeyUsageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApiKeyUsageScalarWhereWithAggregatesInput | Prisma.ApiKeyUsageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ApiKeyUsage"> | string
  apiKeyId?: Prisma.StringWithAggregatesFilter<"ApiKeyUsage"> | string
  endpoint?: Prisma.StringWithAggregatesFilter<"ApiKeyUsage"> | string
  method?: Prisma.StringWithAggregatesFilter<"ApiKeyUsage"> | string
  status?: Prisma.IntWithAggregatesFilter<"ApiKeyUsage"> | number
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"ApiKeyUsage"> | Date | string
  ipAddress?: Prisma.StringNullableWithAggregatesFilter<"ApiKeyUsage"> | string | null
}

export type ApiKeyUsageCreateInput = {
  id?: string
  apiKeyId: string
  endpoint: string
  method: string
  status: number
  timestamp?: Date | string
  ipAddress?: string | null
}

export type ApiKeyUsageUncheckedCreateInput = {
  id?: string
  apiKeyId: string
  endpoint: string
  method: string
  status: number
  timestamp?: Date | string
  ipAddress?: string | null
}

export type ApiKeyUsageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  apiKeyId?: Prisma.StringFieldUpdateOperationsInput | string
  endpoint?: Prisma.StringFieldUpdateOperationsInput | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ApiKeyUsageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  apiKeyId?: Prisma.StringFieldUpdateOperationsInput | string
  endpoint?: Prisma.StringFieldUpdateOperationsInput | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ApiKeyUsageCreateManyInput = {
  id?: string
  apiKeyId: string
  endpoint: string
  method: string
  status: number
  timestamp?: Date | string
  ipAddress?: string | null
}

export type ApiKeyUsageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  apiKeyId?: Prisma.StringFieldUpdateOperationsInput | string
  endpoint?: Prisma.StringFieldUpdateOperationsInput | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ApiKeyUsageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  apiKeyId?: Prisma.StringFieldUpdateOperationsInput | string
  endpoint?: Prisma.StringFieldUpdateOperationsInput | string
  method?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.IntFieldUpdateOperationsInput | number
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ApiKeyUsageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  apiKeyId?: Prisma.SortOrder
  endpoint?: Prisma.SortOrder
  method?: Prisma.SortOrder
  status?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
}

export type ApiKeyUsageAvgOrderByAggregateInput = {
  status?: Prisma.SortOrder
}

export type ApiKeyUsageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  apiKeyId?: Prisma.SortOrder
  endpoint?: Prisma.SortOrder
  method?: Prisma.SortOrder
  status?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
}

export type ApiKeyUsageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  apiKeyId?: Prisma.SortOrder
  endpoint?: Prisma.SortOrder
  method?: Prisma.SortOrder
  status?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
}

export type ApiKeyUsageSumOrderByAggregateInput = {
  status?: Prisma.SortOrder
}



export type ApiKeyUsageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  apiKeyId?: boolean
  endpoint?: boolean
  method?: boolean
  status?: boolean
  timestamp?: boolean
  ipAddress?: boolean
}, ExtArgs["result"]["apiKeyUsage"]>

export type ApiKeyUsageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  apiKeyId?: boolean
  endpoint?: boolean
  method?: boolean
  status?: boolean
  timestamp?: boolean
  ipAddress?: boolean
}, ExtArgs["result"]["apiKeyUsage"]>

export type ApiKeyUsageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  apiKeyId?: boolean
  endpoint?: boolean
  method?: boolean
  status?: boolean
  timestamp?: boolean
  ipAddress?: boolean
}, ExtArgs["result"]["apiKeyUsage"]>

export type ApiKeyUsageSelectScalar = {
  id?: boolean
  apiKeyId?: boolean
  endpoint?: boolean
  method?: boolean
  status?: boolean
  timestamp?: boolean
  ipAddress?: boolean
}

export type ApiKeyUsageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "apiKeyId" | "endpoint" | "method" | "status" | "timestamp" | "ipAddress", ExtArgs["result"]["apiKeyUsage"]>

export type $ApiKeyUsagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ApiKeyUsage"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    apiKeyId: string
    endpoint: string
    method: string
    status: number
    timestamp: Date
    ipAddress: string | null
  }, ExtArgs["result"]["apiKeyUsage"]>
  composites: {}
}

export type ApiKeyUsageGetPayload<S extends boolean | null | undefined | ApiKeyUsageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApiKeyUsagePayload, S>

export type ApiKeyUsageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApiKeyUsageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApiKeyUsageCountAggregateInputType | true
  }

export interface ApiKeyUsageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ApiKeyUsage'], meta: { name: 'ApiKeyUsage' } }
  /**
   * Find zero or one ApiKeyUsage that matches the filter.
   * @param {ApiKeyUsageFindUniqueArgs} args - Arguments to find a ApiKeyUsage
   * @example
   * // Get one ApiKeyUsage
   * const apiKeyUsage = await prisma.apiKeyUsage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApiKeyUsageFindUniqueArgs>(args: Prisma.SelectSubset<T, ApiKeyUsageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApiKeyUsageClient<runtime.Types.Result.GetResult<Prisma.$ApiKeyUsagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ApiKeyUsage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApiKeyUsageFindUniqueOrThrowArgs} args - Arguments to find a ApiKeyUsage
   * @example
   * // Get one ApiKeyUsage
   * const apiKeyUsage = await prisma.apiKeyUsage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApiKeyUsageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApiKeyUsageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApiKeyUsageClient<runtime.Types.Result.GetResult<Prisma.$ApiKeyUsagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApiKeyUsage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiKeyUsageFindFirstArgs} args - Arguments to find a ApiKeyUsage
   * @example
   * // Get one ApiKeyUsage
   * const apiKeyUsage = await prisma.apiKeyUsage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApiKeyUsageFindFirstArgs>(args?: Prisma.SelectSubset<T, ApiKeyUsageFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApiKeyUsageClient<runtime.Types.Result.GetResult<Prisma.$ApiKeyUsagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApiKeyUsage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiKeyUsageFindFirstOrThrowArgs} args - Arguments to find a ApiKeyUsage
   * @example
   * // Get one ApiKeyUsage
   * const apiKeyUsage = await prisma.apiKeyUsage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApiKeyUsageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApiKeyUsageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApiKeyUsageClient<runtime.Types.Result.GetResult<Prisma.$ApiKeyUsagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ApiKeyUsages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiKeyUsageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ApiKeyUsages
   * const apiKeyUsages = await prisma.apiKeyUsage.findMany()
   * 
   * // Get first 10 ApiKeyUsages
   * const apiKeyUsages = await prisma.apiKeyUsage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const apiKeyUsageWithIdOnly = await prisma.apiKeyUsage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApiKeyUsageFindManyArgs>(args?: Prisma.SelectSubset<T, ApiKeyUsageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApiKeyUsagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ApiKeyUsage.
   * @param {ApiKeyUsageCreateArgs} args - Arguments to create a ApiKeyUsage.
   * @example
   * // Create one ApiKeyUsage
   * const ApiKeyUsage = await prisma.apiKeyUsage.create({
   *   data: {
   *     // ... data to create a ApiKeyUsage
   *   }
   * })
   * 
   */
  create<T extends ApiKeyUsageCreateArgs>(args: Prisma.SelectSubset<T, ApiKeyUsageCreateArgs<ExtArgs>>): Prisma.Prisma__ApiKeyUsageClient<runtime.Types.Result.GetResult<Prisma.$ApiKeyUsagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ApiKeyUsages.
   * @param {ApiKeyUsageCreateManyArgs} args - Arguments to create many ApiKeyUsages.
   * @example
   * // Create many ApiKeyUsages
   * const apiKeyUsage = await prisma.apiKeyUsage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApiKeyUsageCreateManyArgs>(args?: Prisma.SelectSubset<T, ApiKeyUsageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ApiKeyUsages and returns the data saved in the database.
   * @param {ApiKeyUsageCreateManyAndReturnArgs} args - Arguments to create many ApiKeyUsages.
   * @example
   * // Create many ApiKeyUsages
   * const apiKeyUsage = await prisma.apiKeyUsage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ApiKeyUsages and only return the `id`
   * const apiKeyUsageWithIdOnly = await prisma.apiKeyUsage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ApiKeyUsageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ApiKeyUsageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApiKeyUsagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ApiKeyUsage.
   * @param {ApiKeyUsageDeleteArgs} args - Arguments to delete one ApiKeyUsage.
   * @example
   * // Delete one ApiKeyUsage
   * const ApiKeyUsage = await prisma.apiKeyUsage.delete({
   *   where: {
   *     // ... filter to delete one ApiKeyUsage
   *   }
   * })
   * 
   */
  delete<T extends ApiKeyUsageDeleteArgs>(args: Prisma.SelectSubset<T, ApiKeyUsageDeleteArgs<ExtArgs>>): Prisma.Prisma__ApiKeyUsageClient<runtime.Types.Result.GetResult<Prisma.$ApiKeyUsagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ApiKeyUsage.
   * @param {ApiKeyUsageUpdateArgs} args - Arguments to update one ApiKeyUsage.
   * @example
   * // Update one ApiKeyUsage
   * const apiKeyUsage = await prisma.apiKeyUsage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApiKeyUsageUpdateArgs>(args: Prisma.SelectSubset<T, ApiKeyUsageUpdateArgs<ExtArgs>>): Prisma.Prisma__ApiKeyUsageClient<runtime.Types.Result.GetResult<Prisma.$ApiKeyUsagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ApiKeyUsages.
   * @param {ApiKeyUsageDeleteManyArgs} args - Arguments to filter ApiKeyUsages to delete.
   * @example
   * // Delete a few ApiKeyUsages
   * const { count } = await prisma.apiKeyUsage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApiKeyUsageDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApiKeyUsageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApiKeyUsages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiKeyUsageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ApiKeyUsages
   * const apiKeyUsage = await prisma.apiKeyUsage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApiKeyUsageUpdateManyArgs>(args: Prisma.SelectSubset<T, ApiKeyUsageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApiKeyUsages and returns the data updated in the database.
   * @param {ApiKeyUsageUpdateManyAndReturnArgs} args - Arguments to update many ApiKeyUsages.
   * @example
   * // Update many ApiKeyUsages
   * const apiKeyUsage = await prisma.apiKeyUsage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ApiKeyUsages and only return the `id`
   * const apiKeyUsageWithIdOnly = await prisma.apiKeyUsage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ApiKeyUsageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ApiKeyUsageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApiKeyUsagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ApiKeyUsage.
   * @param {ApiKeyUsageUpsertArgs} args - Arguments to update or create a ApiKeyUsage.
   * @example
   * // Update or create a ApiKeyUsage
   * const apiKeyUsage = await prisma.apiKeyUsage.upsert({
   *   create: {
   *     // ... data to create a ApiKeyUsage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ApiKeyUsage we want to update
   *   }
   * })
   */
  upsert<T extends ApiKeyUsageUpsertArgs>(args: Prisma.SelectSubset<T, ApiKeyUsageUpsertArgs<ExtArgs>>): Prisma.Prisma__ApiKeyUsageClient<runtime.Types.Result.GetResult<Prisma.$ApiKeyUsagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ApiKeyUsages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiKeyUsageCountArgs} args - Arguments to filter ApiKeyUsages to count.
   * @example
   * // Count the number of ApiKeyUsages
   * const count = await prisma.apiKeyUsage.count({
   *   where: {
   *     // ... the filter for the ApiKeyUsages we want to count
   *   }
   * })
  **/
  count<T extends ApiKeyUsageCountArgs>(
    args?: Prisma.Subset<T, ApiKeyUsageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApiKeyUsageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ApiKeyUsage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiKeyUsageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApiKeyUsageAggregateArgs>(args: Prisma.Subset<T, ApiKeyUsageAggregateArgs>): Prisma.PrismaPromise<GetApiKeyUsageAggregateType<T>>

  /**
   * Group by ApiKeyUsage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApiKeyUsageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApiKeyUsageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApiKeyUsageGroupByArgs['orderBy'] }
      : { orderBy?: ApiKeyUsageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApiKeyUsageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApiKeyUsageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ApiKeyUsage model
 */
readonly fields: ApiKeyUsageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ApiKeyUsage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApiKeyUsageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ApiKeyUsage model
 */
export interface ApiKeyUsageFieldRefs {
  readonly id: Prisma.FieldRef<"ApiKeyUsage", 'String'>
  readonly apiKeyId: Prisma.FieldRef<"ApiKeyUsage", 'String'>
  readonly endpoint: Prisma.FieldRef<"ApiKeyUsage", 'String'>
  readonly method: Prisma.FieldRef<"ApiKeyUsage", 'String'>
  readonly status: Prisma.FieldRef<"ApiKeyUsage", 'Int'>
  readonly timestamp: Prisma.FieldRef<"ApiKeyUsage", 'DateTime'>
  readonly ipAddress: Prisma.FieldRef<"ApiKeyUsage", 'String'>
}
    

// Custom InputTypes
/**
 * ApiKeyUsage findUnique
 */
export type ApiKeyUsageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiKeyUsage
   */
  select?: Prisma.ApiKeyUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiKeyUsage
   */
  omit?: Prisma.ApiKeyUsageOmit<ExtArgs> | null
  /**
   * Filter, which ApiKeyUsage to fetch.
   */
  where: Prisma.ApiKeyUsageWhereUniqueInput
}

/**
 * ApiKeyUsage findUniqueOrThrow
 */
export type ApiKeyUsageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiKeyUsage
   */
  select?: Prisma.ApiKeyUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiKeyUsage
   */
  omit?: Prisma.ApiKeyUsageOmit<ExtArgs> | null
  /**
   * Filter, which ApiKeyUsage to fetch.
   */
  where: Prisma.ApiKeyUsageWhereUniqueInput
}

/**
 * ApiKeyUsage findFirst
 */
export type ApiKeyUsageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiKeyUsage
   */
  select?: Prisma.ApiKeyUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiKeyUsage
   */
  omit?: Prisma.ApiKeyUsageOmit<ExtArgs> | null
  /**
   * Filter, which ApiKeyUsage to fetch.
   */
  where?: Prisma.ApiKeyUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApiKeyUsages to fetch.
   */
  orderBy?: Prisma.ApiKeyUsageOrderByWithRelationInput | Prisma.ApiKeyUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApiKeyUsages.
   */
  cursor?: Prisma.ApiKeyUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApiKeyUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApiKeyUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApiKeyUsages.
   */
  distinct?: Prisma.ApiKeyUsageScalarFieldEnum | Prisma.ApiKeyUsageScalarFieldEnum[]
}

/**
 * ApiKeyUsage findFirstOrThrow
 */
export type ApiKeyUsageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiKeyUsage
   */
  select?: Prisma.ApiKeyUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiKeyUsage
   */
  omit?: Prisma.ApiKeyUsageOmit<ExtArgs> | null
  /**
   * Filter, which ApiKeyUsage to fetch.
   */
  where?: Prisma.ApiKeyUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApiKeyUsages to fetch.
   */
  orderBy?: Prisma.ApiKeyUsageOrderByWithRelationInput | Prisma.ApiKeyUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApiKeyUsages.
   */
  cursor?: Prisma.ApiKeyUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApiKeyUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApiKeyUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApiKeyUsages.
   */
  distinct?: Prisma.ApiKeyUsageScalarFieldEnum | Prisma.ApiKeyUsageScalarFieldEnum[]
}

/**
 * ApiKeyUsage findMany
 */
export type ApiKeyUsageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiKeyUsage
   */
  select?: Prisma.ApiKeyUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiKeyUsage
   */
  omit?: Prisma.ApiKeyUsageOmit<ExtArgs> | null
  /**
   * Filter, which ApiKeyUsages to fetch.
   */
  where?: Prisma.ApiKeyUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApiKeyUsages to fetch.
   */
  orderBy?: Prisma.ApiKeyUsageOrderByWithRelationInput | Prisma.ApiKeyUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ApiKeyUsages.
   */
  cursor?: Prisma.ApiKeyUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApiKeyUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApiKeyUsages.
   */
  skip?: number
  distinct?: Prisma.ApiKeyUsageScalarFieldEnum | Prisma.ApiKeyUsageScalarFieldEnum[]
}

/**
 * ApiKeyUsage create
 */
export type ApiKeyUsageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiKeyUsage
   */
  select?: Prisma.ApiKeyUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiKeyUsage
   */
  omit?: Prisma.ApiKeyUsageOmit<ExtArgs> | null
  /**
   * The data needed to create a ApiKeyUsage.
   */
  data: Prisma.XOR<Prisma.ApiKeyUsageCreateInput, Prisma.ApiKeyUsageUncheckedCreateInput>
}

/**
 * ApiKeyUsage createMany
 */
export type ApiKeyUsageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ApiKeyUsages.
   */
  data: Prisma.ApiKeyUsageCreateManyInput | Prisma.ApiKeyUsageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ApiKeyUsage createManyAndReturn
 */
export type ApiKeyUsageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiKeyUsage
   */
  select?: Prisma.ApiKeyUsageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApiKeyUsage
   */
  omit?: Prisma.ApiKeyUsageOmit<ExtArgs> | null
  /**
   * The data used to create many ApiKeyUsages.
   */
  data: Prisma.ApiKeyUsageCreateManyInput | Prisma.ApiKeyUsageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ApiKeyUsage update
 */
export type ApiKeyUsageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiKeyUsage
   */
  select?: Prisma.ApiKeyUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiKeyUsage
   */
  omit?: Prisma.ApiKeyUsageOmit<ExtArgs> | null
  /**
   * The data needed to update a ApiKeyUsage.
   */
  data: Prisma.XOR<Prisma.ApiKeyUsageUpdateInput, Prisma.ApiKeyUsageUncheckedUpdateInput>
  /**
   * Choose, which ApiKeyUsage to update.
   */
  where: Prisma.ApiKeyUsageWhereUniqueInput
}

/**
 * ApiKeyUsage updateMany
 */
export type ApiKeyUsageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ApiKeyUsages.
   */
  data: Prisma.XOR<Prisma.ApiKeyUsageUpdateManyMutationInput, Prisma.ApiKeyUsageUncheckedUpdateManyInput>
  /**
   * Filter which ApiKeyUsages to update
   */
  where?: Prisma.ApiKeyUsageWhereInput
  /**
   * Limit how many ApiKeyUsages to update.
   */
  limit?: number
}

/**
 * ApiKeyUsage updateManyAndReturn
 */
export type ApiKeyUsageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiKeyUsage
   */
  select?: Prisma.ApiKeyUsageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApiKeyUsage
   */
  omit?: Prisma.ApiKeyUsageOmit<ExtArgs> | null
  /**
   * The data used to update ApiKeyUsages.
   */
  data: Prisma.XOR<Prisma.ApiKeyUsageUpdateManyMutationInput, Prisma.ApiKeyUsageUncheckedUpdateManyInput>
  /**
   * Filter which ApiKeyUsages to update
   */
  where?: Prisma.ApiKeyUsageWhereInput
  /**
   * Limit how many ApiKeyUsages to update.
   */
  limit?: number
}

/**
 * ApiKeyUsage upsert
 */
export type ApiKeyUsageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiKeyUsage
   */
  select?: Prisma.ApiKeyUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiKeyUsage
   */
  omit?: Prisma.ApiKeyUsageOmit<ExtArgs> | null
  /**
   * The filter to search for the ApiKeyUsage to update in case it exists.
   */
  where: Prisma.ApiKeyUsageWhereUniqueInput
  /**
   * In case the ApiKeyUsage found by the `where` argument doesn't exist, create a new ApiKeyUsage with this data.
   */
  create: Prisma.XOR<Prisma.ApiKeyUsageCreateInput, Prisma.ApiKeyUsageUncheckedCreateInput>
  /**
   * In case the ApiKeyUsage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApiKeyUsageUpdateInput, Prisma.ApiKeyUsageUncheckedUpdateInput>
}

/**
 * ApiKeyUsage delete
 */
export type ApiKeyUsageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiKeyUsage
   */
  select?: Prisma.ApiKeyUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiKeyUsage
   */
  omit?: Prisma.ApiKeyUsageOmit<ExtArgs> | null
  /**
   * Filter which ApiKeyUsage to delete.
   */
  where: Prisma.ApiKeyUsageWhereUniqueInput
}

/**
 * ApiKeyUsage deleteMany
 */
export type ApiKeyUsageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApiKeyUsages to delete
   */
  where?: Prisma.ApiKeyUsageWhereInput
  /**
   * Limit how many ApiKeyUsages to delete.
   */
  limit?: number
}

/**
 * ApiKeyUsage without action
 */
export type ApiKeyUsageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApiKeyUsage
   */
  select?: Prisma.ApiKeyUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApiKeyUsage
   */
  omit?: Prisma.ApiKeyUsageOmit<ExtArgs> | null
}
