
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BannedDomain` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BannedDomain
 * 
 */
export type BannedDomainModel = runtime.Types.Result.DefaultSelection<Prisma.$BannedDomainPayload>

export type AggregateBannedDomain = {
  _count: BannedDomainCountAggregateOutputType | null
  _min: BannedDomainMinAggregateOutputType | null
  _max: BannedDomainMaxAggregateOutputType | null
}

export type BannedDomainMinAggregateOutputType = {
  id: string | null
  domain: string | null
  reason: string | null
  bannedAt: Date | null
  bannedBy: string | null
}

export type BannedDomainMaxAggregateOutputType = {
  id: string | null
  domain: string | null
  reason: string | null
  bannedAt: Date | null
  bannedBy: string | null
}

export type BannedDomainCountAggregateOutputType = {
  id: number
  domain: number
  reason: number
  bannedAt: number
  bannedBy: number
  _all: number
}


export type BannedDomainMinAggregateInputType = {
  id?: true
  domain?: true
  reason?: true
  bannedAt?: true
  bannedBy?: true
}

export type BannedDomainMaxAggregateInputType = {
  id?: true
  domain?: true
  reason?: true
  bannedAt?: true
  bannedBy?: true
}

export type BannedDomainCountAggregateInputType = {
  id?: true
  domain?: true
  reason?: true
  bannedAt?: true
  bannedBy?: true
  _all?: true
}

export type BannedDomainAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BannedDomain to aggregate.
   */
  where?: Prisma.BannedDomainWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BannedDomains to fetch.
   */
  orderBy?: Prisma.BannedDomainOrderByWithRelationInput | Prisma.BannedDomainOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BannedDomainWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BannedDomains from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BannedDomains.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BannedDomains
  **/
  _count?: true | BannedDomainCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BannedDomainMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BannedDomainMaxAggregateInputType
}

export type GetBannedDomainAggregateType<T extends BannedDomainAggregateArgs> = {
      [P in keyof T & keyof AggregateBannedDomain]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBannedDomain[P]>
    : Prisma.GetScalarType<T[P], AggregateBannedDomain[P]>
}




export type BannedDomainGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BannedDomainWhereInput
  orderBy?: Prisma.BannedDomainOrderByWithAggregationInput | Prisma.BannedDomainOrderByWithAggregationInput[]
  by: Prisma.BannedDomainScalarFieldEnum[] | Prisma.BannedDomainScalarFieldEnum
  having?: Prisma.BannedDomainScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BannedDomainCountAggregateInputType | true
  _min?: BannedDomainMinAggregateInputType
  _max?: BannedDomainMaxAggregateInputType
}

export type BannedDomainGroupByOutputType = {
  id: string
  domain: string
  reason: string | null
  bannedAt: Date
  bannedBy: string
  _count: BannedDomainCountAggregateOutputType | null
  _min: BannedDomainMinAggregateOutputType | null
  _max: BannedDomainMaxAggregateOutputType | null
}

type GetBannedDomainGroupByPayload<T extends BannedDomainGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BannedDomainGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BannedDomainGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BannedDomainGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BannedDomainGroupByOutputType[P]>
      }
    >
  >



export type BannedDomainWhereInput = {
  AND?: Prisma.BannedDomainWhereInput | Prisma.BannedDomainWhereInput[]
  OR?: Prisma.BannedDomainWhereInput[]
  NOT?: Prisma.BannedDomainWhereInput | Prisma.BannedDomainWhereInput[]
  id?: Prisma.StringFilter<"BannedDomain"> | string
  domain?: Prisma.StringFilter<"BannedDomain"> | string
  reason?: Prisma.StringNullableFilter<"BannedDomain"> | string | null
  bannedAt?: Prisma.DateTimeFilter<"BannedDomain"> | Date | string
  bannedBy?: Prisma.StringFilter<"BannedDomain"> | string
}

export type BannedDomainOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  domain?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  bannedAt?: Prisma.SortOrder
  bannedBy?: Prisma.SortOrder
}

export type BannedDomainWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  domain?: string
  AND?: Prisma.BannedDomainWhereInput | Prisma.BannedDomainWhereInput[]
  OR?: Prisma.BannedDomainWhereInput[]
  NOT?: Prisma.BannedDomainWhereInput | Prisma.BannedDomainWhereInput[]
  reason?: Prisma.StringNullableFilter<"BannedDomain"> | string | null
  bannedAt?: Prisma.DateTimeFilter<"BannedDomain"> | Date | string
  bannedBy?: Prisma.StringFilter<"BannedDomain"> | string
}, "id" | "domain">

export type BannedDomainOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  domain?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  bannedAt?: Prisma.SortOrder
  bannedBy?: Prisma.SortOrder
  _count?: Prisma.BannedDomainCountOrderByAggregateInput
  _max?: Prisma.BannedDomainMaxOrderByAggregateInput
  _min?: Prisma.BannedDomainMinOrderByAggregateInput
}

export type BannedDomainScalarWhereWithAggregatesInput = {
  AND?: Prisma.BannedDomainScalarWhereWithAggregatesInput | Prisma.BannedDomainScalarWhereWithAggregatesInput[]
  OR?: Prisma.BannedDomainScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BannedDomainScalarWhereWithAggregatesInput | Prisma.BannedDomainScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BannedDomain"> | string
  domain?: Prisma.StringWithAggregatesFilter<"BannedDomain"> | string
  reason?: Prisma.StringNullableWithAggregatesFilter<"BannedDomain"> | string | null
  bannedAt?: Prisma.DateTimeWithAggregatesFilter<"BannedDomain"> | Date | string
  bannedBy?: Prisma.StringWithAggregatesFilter<"BannedDomain"> | string
}

export type BannedDomainCreateInput = {
  id?: string
  domain: string
  reason?: string | null
  bannedAt?: Date | string
  bannedBy: string
}

export type BannedDomainUncheckedCreateInput = {
  id?: string
  domain: string
  reason?: string | null
  bannedAt?: Date | string
  bannedBy: string
}

export type BannedDomainUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bannedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bannedBy?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BannedDomainUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bannedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bannedBy?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BannedDomainCreateManyInput = {
  id?: string
  domain: string
  reason?: string | null
  bannedAt?: Date | string
  bannedBy: string
}

export type BannedDomainUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bannedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bannedBy?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BannedDomainUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bannedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bannedBy?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BannedDomainCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  domain?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  bannedAt?: Prisma.SortOrder
  bannedBy?: Prisma.SortOrder
}

export type BannedDomainMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  domain?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  bannedAt?: Prisma.SortOrder
  bannedBy?: Prisma.SortOrder
}

export type BannedDomainMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  domain?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  bannedAt?: Prisma.SortOrder
  bannedBy?: Prisma.SortOrder
}



export type BannedDomainSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  domain?: boolean
  reason?: boolean
  bannedAt?: boolean
  bannedBy?: boolean
}, ExtArgs["result"]["bannedDomain"]>

export type BannedDomainSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  domain?: boolean
  reason?: boolean
  bannedAt?: boolean
  bannedBy?: boolean
}, ExtArgs["result"]["bannedDomain"]>

export type BannedDomainSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  domain?: boolean
  reason?: boolean
  bannedAt?: boolean
  bannedBy?: boolean
}, ExtArgs["result"]["bannedDomain"]>

export type BannedDomainSelectScalar = {
  id?: boolean
  domain?: boolean
  reason?: boolean
  bannedAt?: boolean
  bannedBy?: boolean
}

export type BannedDomainOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "domain" | "reason" | "bannedAt" | "bannedBy", ExtArgs["result"]["bannedDomain"]>

export type $BannedDomainPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BannedDomain"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    domain: string
    reason: string | null
    bannedAt: Date
    bannedBy: string
  }, ExtArgs["result"]["bannedDomain"]>
  composites: {}
}

export type BannedDomainGetPayload<S extends boolean | null | undefined | BannedDomainDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BannedDomainPayload, S>

export type BannedDomainCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BannedDomainFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BannedDomainCountAggregateInputType | true
  }

export interface BannedDomainDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BannedDomain'], meta: { name: 'BannedDomain' } }
  /**
   * Find zero or one BannedDomain that matches the filter.
   * @param {BannedDomainFindUniqueArgs} args - Arguments to find a BannedDomain
   * @example
   * // Get one BannedDomain
   * const bannedDomain = await prisma.bannedDomain.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BannedDomainFindUniqueArgs>(args: Prisma.SelectSubset<T, BannedDomainFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BannedDomainClient<runtime.Types.Result.GetResult<Prisma.$BannedDomainPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BannedDomain that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BannedDomainFindUniqueOrThrowArgs} args - Arguments to find a BannedDomain
   * @example
   * // Get one BannedDomain
   * const bannedDomain = await prisma.bannedDomain.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BannedDomainFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BannedDomainFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BannedDomainClient<runtime.Types.Result.GetResult<Prisma.$BannedDomainPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BannedDomain that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedDomainFindFirstArgs} args - Arguments to find a BannedDomain
   * @example
   * // Get one BannedDomain
   * const bannedDomain = await prisma.bannedDomain.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BannedDomainFindFirstArgs>(args?: Prisma.SelectSubset<T, BannedDomainFindFirstArgs<ExtArgs>>): Prisma.Prisma__BannedDomainClient<runtime.Types.Result.GetResult<Prisma.$BannedDomainPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BannedDomain that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedDomainFindFirstOrThrowArgs} args - Arguments to find a BannedDomain
   * @example
   * // Get one BannedDomain
   * const bannedDomain = await prisma.bannedDomain.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BannedDomainFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BannedDomainFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BannedDomainClient<runtime.Types.Result.GetResult<Prisma.$BannedDomainPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BannedDomains that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedDomainFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BannedDomains
   * const bannedDomains = await prisma.bannedDomain.findMany()
   * 
   * // Get first 10 BannedDomains
   * const bannedDomains = await prisma.bannedDomain.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bannedDomainWithIdOnly = await prisma.bannedDomain.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BannedDomainFindManyArgs>(args?: Prisma.SelectSubset<T, BannedDomainFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BannedDomainPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BannedDomain.
   * @param {BannedDomainCreateArgs} args - Arguments to create a BannedDomain.
   * @example
   * // Create one BannedDomain
   * const BannedDomain = await prisma.bannedDomain.create({
   *   data: {
   *     // ... data to create a BannedDomain
   *   }
   * })
   * 
   */
  create<T extends BannedDomainCreateArgs>(args: Prisma.SelectSubset<T, BannedDomainCreateArgs<ExtArgs>>): Prisma.Prisma__BannedDomainClient<runtime.Types.Result.GetResult<Prisma.$BannedDomainPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BannedDomains.
   * @param {BannedDomainCreateManyArgs} args - Arguments to create many BannedDomains.
   * @example
   * // Create many BannedDomains
   * const bannedDomain = await prisma.bannedDomain.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BannedDomainCreateManyArgs>(args?: Prisma.SelectSubset<T, BannedDomainCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BannedDomains and returns the data saved in the database.
   * @param {BannedDomainCreateManyAndReturnArgs} args - Arguments to create many BannedDomains.
   * @example
   * // Create many BannedDomains
   * const bannedDomain = await prisma.bannedDomain.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BannedDomains and only return the `id`
   * const bannedDomainWithIdOnly = await prisma.bannedDomain.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BannedDomainCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BannedDomainCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BannedDomainPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BannedDomain.
   * @param {BannedDomainDeleteArgs} args - Arguments to delete one BannedDomain.
   * @example
   * // Delete one BannedDomain
   * const BannedDomain = await prisma.bannedDomain.delete({
   *   where: {
   *     // ... filter to delete one BannedDomain
   *   }
   * })
   * 
   */
  delete<T extends BannedDomainDeleteArgs>(args: Prisma.SelectSubset<T, BannedDomainDeleteArgs<ExtArgs>>): Prisma.Prisma__BannedDomainClient<runtime.Types.Result.GetResult<Prisma.$BannedDomainPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BannedDomain.
   * @param {BannedDomainUpdateArgs} args - Arguments to update one BannedDomain.
   * @example
   * // Update one BannedDomain
   * const bannedDomain = await prisma.bannedDomain.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BannedDomainUpdateArgs>(args: Prisma.SelectSubset<T, BannedDomainUpdateArgs<ExtArgs>>): Prisma.Prisma__BannedDomainClient<runtime.Types.Result.GetResult<Prisma.$BannedDomainPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BannedDomains.
   * @param {BannedDomainDeleteManyArgs} args - Arguments to filter BannedDomains to delete.
   * @example
   * // Delete a few BannedDomains
   * const { count } = await prisma.bannedDomain.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BannedDomainDeleteManyArgs>(args?: Prisma.SelectSubset<T, BannedDomainDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BannedDomains.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedDomainUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BannedDomains
   * const bannedDomain = await prisma.bannedDomain.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BannedDomainUpdateManyArgs>(args: Prisma.SelectSubset<T, BannedDomainUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BannedDomains and returns the data updated in the database.
   * @param {BannedDomainUpdateManyAndReturnArgs} args - Arguments to update many BannedDomains.
   * @example
   * // Update many BannedDomains
   * const bannedDomain = await prisma.bannedDomain.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BannedDomains and only return the `id`
   * const bannedDomainWithIdOnly = await prisma.bannedDomain.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BannedDomainUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BannedDomainUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BannedDomainPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BannedDomain.
   * @param {BannedDomainUpsertArgs} args - Arguments to update or create a BannedDomain.
   * @example
   * // Update or create a BannedDomain
   * const bannedDomain = await prisma.bannedDomain.upsert({
   *   create: {
   *     // ... data to create a BannedDomain
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BannedDomain we want to update
   *   }
   * })
   */
  upsert<T extends BannedDomainUpsertArgs>(args: Prisma.SelectSubset<T, BannedDomainUpsertArgs<ExtArgs>>): Prisma.Prisma__BannedDomainClient<runtime.Types.Result.GetResult<Prisma.$BannedDomainPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BannedDomains.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedDomainCountArgs} args - Arguments to filter BannedDomains to count.
   * @example
   * // Count the number of BannedDomains
   * const count = await prisma.bannedDomain.count({
   *   where: {
   *     // ... the filter for the BannedDomains we want to count
   *   }
   * })
  **/
  count<T extends BannedDomainCountArgs>(
    args?: Prisma.Subset<T, BannedDomainCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BannedDomainCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BannedDomain.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedDomainAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BannedDomainAggregateArgs>(args: Prisma.Subset<T, BannedDomainAggregateArgs>): Prisma.PrismaPromise<GetBannedDomainAggregateType<T>>

  /**
   * Group by BannedDomain.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BannedDomainGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BannedDomainGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BannedDomainGroupByArgs['orderBy'] }
      : { orderBy?: BannedDomainGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BannedDomainGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBannedDomainGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BannedDomain model
 */
readonly fields: BannedDomainFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BannedDomain.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BannedDomainClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BannedDomain model
 */
export interface BannedDomainFieldRefs {
  readonly id: Prisma.FieldRef<"BannedDomain", 'String'>
  readonly domain: Prisma.FieldRef<"BannedDomain", 'String'>
  readonly reason: Prisma.FieldRef<"BannedDomain", 'String'>
  readonly bannedAt: Prisma.FieldRef<"BannedDomain", 'DateTime'>
  readonly bannedBy: Prisma.FieldRef<"BannedDomain", 'String'>
}
    

// Custom InputTypes
/**
 * BannedDomain findUnique
 */
export type BannedDomainFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedDomain
   */
  select?: Prisma.BannedDomainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedDomain
   */
  omit?: Prisma.BannedDomainOmit<ExtArgs> | null
  /**
   * Filter, which BannedDomain to fetch.
   */
  where: Prisma.BannedDomainWhereUniqueInput
}

/**
 * BannedDomain findUniqueOrThrow
 */
export type BannedDomainFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedDomain
   */
  select?: Prisma.BannedDomainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedDomain
   */
  omit?: Prisma.BannedDomainOmit<ExtArgs> | null
  /**
   * Filter, which BannedDomain to fetch.
   */
  where: Prisma.BannedDomainWhereUniqueInput
}

/**
 * BannedDomain findFirst
 */
export type BannedDomainFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedDomain
   */
  select?: Prisma.BannedDomainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedDomain
   */
  omit?: Prisma.BannedDomainOmit<ExtArgs> | null
  /**
   * Filter, which BannedDomain to fetch.
   */
  where?: Prisma.BannedDomainWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BannedDomains to fetch.
   */
  orderBy?: Prisma.BannedDomainOrderByWithRelationInput | Prisma.BannedDomainOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BannedDomains.
   */
  cursor?: Prisma.BannedDomainWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BannedDomains from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BannedDomains.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BannedDomains.
   */
  distinct?: Prisma.BannedDomainScalarFieldEnum | Prisma.BannedDomainScalarFieldEnum[]
}

/**
 * BannedDomain findFirstOrThrow
 */
export type BannedDomainFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedDomain
   */
  select?: Prisma.BannedDomainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedDomain
   */
  omit?: Prisma.BannedDomainOmit<ExtArgs> | null
  /**
   * Filter, which BannedDomain to fetch.
   */
  where?: Prisma.BannedDomainWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BannedDomains to fetch.
   */
  orderBy?: Prisma.BannedDomainOrderByWithRelationInput | Prisma.BannedDomainOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BannedDomains.
   */
  cursor?: Prisma.BannedDomainWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BannedDomains from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BannedDomains.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BannedDomains.
   */
  distinct?: Prisma.BannedDomainScalarFieldEnum | Prisma.BannedDomainScalarFieldEnum[]
}

/**
 * BannedDomain findMany
 */
export type BannedDomainFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedDomain
   */
  select?: Prisma.BannedDomainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedDomain
   */
  omit?: Prisma.BannedDomainOmit<ExtArgs> | null
  /**
   * Filter, which BannedDomains to fetch.
   */
  where?: Prisma.BannedDomainWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BannedDomains to fetch.
   */
  orderBy?: Prisma.BannedDomainOrderByWithRelationInput | Prisma.BannedDomainOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BannedDomains.
   */
  cursor?: Prisma.BannedDomainWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BannedDomains from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BannedDomains.
   */
  skip?: number
  distinct?: Prisma.BannedDomainScalarFieldEnum | Prisma.BannedDomainScalarFieldEnum[]
}

/**
 * BannedDomain create
 */
export type BannedDomainCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedDomain
   */
  select?: Prisma.BannedDomainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedDomain
   */
  omit?: Prisma.BannedDomainOmit<ExtArgs> | null
  /**
   * The data needed to create a BannedDomain.
   */
  data: Prisma.XOR<Prisma.BannedDomainCreateInput, Prisma.BannedDomainUncheckedCreateInput>
}

/**
 * BannedDomain createMany
 */
export type BannedDomainCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BannedDomains.
   */
  data: Prisma.BannedDomainCreateManyInput | Prisma.BannedDomainCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BannedDomain createManyAndReturn
 */
export type BannedDomainCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedDomain
   */
  select?: Prisma.BannedDomainSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BannedDomain
   */
  omit?: Prisma.BannedDomainOmit<ExtArgs> | null
  /**
   * The data used to create many BannedDomains.
   */
  data: Prisma.BannedDomainCreateManyInput | Prisma.BannedDomainCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BannedDomain update
 */
export type BannedDomainUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedDomain
   */
  select?: Prisma.BannedDomainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedDomain
   */
  omit?: Prisma.BannedDomainOmit<ExtArgs> | null
  /**
   * The data needed to update a BannedDomain.
   */
  data: Prisma.XOR<Prisma.BannedDomainUpdateInput, Prisma.BannedDomainUncheckedUpdateInput>
  /**
   * Choose, which BannedDomain to update.
   */
  where: Prisma.BannedDomainWhereUniqueInput
}

/**
 * BannedDomain updateMany
 */
export type BannedDomainUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BannedDomains.
   */
  data: Prisma.XOR<Prisma.BannedDomainUpdateManyMutationInput, Prisma.BannedDomainUncheckedUpdateManyInput>
  /**
   * Filter which BannedDomains to update
   */
  where?: Prisma.BannedDomainWhereInput
  /**
   * Limit how many BannedDomains to update.
   */
  limit?: number
}

/**
 * BannedDomain updateManyAndReturn
 */
export type BannedDomainUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedDomain
   */
  select?: Prisma.BannedDomainSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BannedDomain
   */
  omit?: Prisma.BannedDomainOmit<ExtArgs> | null
  /**
   * The data used to update BannedDomains.
   */
  data: Prisma.XOR<Prisma.BannedDomainUpdateManyMutationInput, Prisma.BannedDomainUncheckedUpdateManyInput>
  /**
   * Filter which BannedDomains to update
   */
  where?: Prisma.BannedDomainWhereInput
  /**
   * Limit how many BannedDomains to update.
   */
  limit?: number
}

/**
 * BannedDomain upsert
 */
export type BannedDomainUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedDomain
   */
  select?: Prisma.BannedDomainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedDomain
   */
  omit?: Prisma.BannedDomainOmit<ExtArgs> | null
  /**
   * The filter to search for the BannedDomain to update in case it exists.
   */
  where: Prisma.BannedDomainWhereUniqueInput
  /**
   * In case the BannedDomain found by the `where` argument doesn't exist, create a new BannedDomain with this data.
   */
  create: Prisma.XOR<Prisma.BannedDomainCreateInput, Prisma.BannedDomainUncheckedCreateInput>
  /**
   * In case the BannedDomain was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BannedDomainUpdateInput, Prisma.BannedDomainUncheckedUpdateInput>
}

/**
 * BannedDomain delete
 */
export type BannedDomainDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedDomain
   */
  select?: Prisma.BannedDomainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedDomain
   */
  omit?: Prisma.BannedDomainOmit<ExtArgs> | null
  /**
   * Filter which BannedDomain to delete.
   */
  where: Prisma.BannedDomainWhereUniqueInput
}

/**
 * BannedDomain deleteMany
 */
export type BannedDomainDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BannedDomains to delete
   */
  where?: Prisma.BannedDomainWhereInput
  /**
   * Limit how many BannedDomains to delete.
   */
  limit?: number
}

/**
 * BannedDomain without action
 */
export type BannedDomainDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BannedDomain
   */
  select?: Prisma.BannedDomainSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BannedDomain
   */
  omit?: Prisma.BannedDomainOmit<ExtArgs> | null
}
