
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LinkMetadata` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LinkMetadata
 * 
 */
export type LinkMetadataModel = runtime.Types.Result.DefaultSelection<Prisma.$LinkMetadataPayload>

export type AggregateLinkMetadata = {
  _count: LinkMetadataCountAggregateOutputType | null
  _min: LinkMetadataMinAggregateOutputType | null
  _max: LinkMetadataMaxAggregateOutputType | null
}

export type LinkMetadataMinAggregateOutputType = {
  id: string | null
  urlId: string | null
  title: string | null
  description: string | null
  image: string | null
  logo: string | null
  author: string | null
  publisher: string | null
  date: Date | null
  favicon: string | null
  scrapedAt: Date | null
}

export type LinkMetadataMaxAggregateOutputType = {
  id: string | null
  urlId: string | null
  title: string | null
  description: string | null
  image: string | null
  logo: string | null
  author: string | null
  publisher: string | null
  date: Date | null
  favicon: string | null
  scrapedAt: Date | null
}

export type LinkMetadataCountAggregateOutputType = {
  id: number
  urlId: number
  title: number
  description: number
  image: number
  logo: number
  author: number
  publisher: number
  date: number
  favicon: number
  scrapedAt: number
  _all: number
}


export type LinkMetadataMinAggregateInputType = {
  id?: true
  urlId?: true
  title?: true
  description?: true
  image?: true
  logo?: true
  author?: true
  publisher?: true
  date?: true
  favicon?: true
  scrapedAt?: true
}

export type LinkMetadataMaxAggregateInputType = {
  id?: true
  urlId?: true
  title?: true
  description?: true
  image?: true
  logo?: true
  author?: true
  publisher?: true
  date?: true
  favicon?: true
  scrapedAt?: true
}

export type LinkMetadataCountAggregateInputType = {
  id?: true
  urlId?: true
  title?: true
  description?: true
  image?: true
  logo?: true
  author?: true
  publisher?: true
  date?: true
  favicon?: true
  scrapedAt?: true
  _all?: true
}

export type LinkMetadataAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LinkMetadata to aggregate.
   */
  where?: Prisma.LinkMetadataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LinkMetadata to fetch.
   */
  orderBy?: Prisma.LinkMetadataOrderByWithRelationInput | Prisma.LinkMetadataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LinkMetadataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LinkMetadata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LinkMetadata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LinkMetadata
  **/
  _count?: true | LinkMetadataCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LinkMetadataMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LinkMetadataMaxAggregateInputType
}

export type GetLinkMetadataAggregateType<T extends LinkMetadataAggregateArgs> = {
      [P in keyof T & keyof AggregateLinkMetadata]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLinkMetadata[P]>
    : Prisma.GetScalarType<T[P], AggregateLinkMetadata[P]>
}




export type LinkMetadataGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LinkMetadataWhereInput
  orderBy?: Prisma.LinkMetadataOrderByWithAggregationInput | Prisma.LinkMetadataOrderByWithAggregationInput[]
  by: Prisma.LinkMetadataScalarFieldEnum[] | Prisma.LinkMetadataScalarFieldEnum
  having?: Prisma.LinkMetadataScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LinkMetadataCountAggregateInputType | true
  _min?: LinkMetadataMinAggregateInputType
  _max?: LinkMetadataMaxAggregateInputType
}

export type LinkMetadataGroupByOutputType = {
  id: string
  urlId: string
  title: string | null
  description: string | null
  image: string | null
  logo: string | null
  author: string | null
  publisher: string | null
  date: Date | null
  favicon: string | null
  scrapedAt: Date
  _count: LinkMetadataCountAggregateOutputType | null
  _min: LinkMetadataMinAggregateOutputType | null
  _max: LinkMetadataMaxAggregateOutputType | null
}

type GetLinkMetadataGroupByPayload<T extends LinkMetadataGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LinkMetadataGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LinkMetadataGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LinkMetadataGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LinkMetadataGroupByOutputType[P]>
      }
    >
  >



export type LinkMetadataWhereInput = {
  AND?: Prisma.LinkMetadataWhereInput | Prisma.LinkMetadataWhereInput[]
  OR?: Prisma.LinkMetadataWhereInput[]
  NOT?: Prisma.LinkMetadataWhereInput | Prisma.LinkMetadataWhereInput[]
  id?: Prisma.StringFilter<"LinkMetadata"> | string
  urlId?: Prisma.StringFilter<"LinkMetadata"> | string
  title?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  description?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  image?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  logo?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  author?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  publisher?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  date?: Prisma.DateTimeNullableFilter<"LinkMetadata"> | Date | string | null
  favicon?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  scrapedAt?: Prisma.DateTimeFilter<"LinkMetadata"> | Date | string
  url?: Prisma.XOR<Prisma.UrlScalarRelationFilter, Prisma.UrlWhereInput>
}

export type LinkMetadataOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  logo?: Prisma.SortOrderInput | Prisma.SortOrder
  author?: Prisma.SortOrderInput | Prisma.SortOrder
  publisher?: Prisma.SortOrderInput | Prisma.SortOrder
  date?: Prisma.SortOrderInput | Prisma.SortOrder
  favicon?: Prisma.SortOrderInput | Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
  url?: Prisma.UrlOrderByWithRelationInput
}

export type LinkMetadataWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  urlId?: string
  AND?: Prisma.LinkMetadataWhereInput | Prisma.LinkMetadataWhereInput[]
  OR?: Prisma.LinkMetadataWhereInput[]
  NOT?: Prisma.LinkMetadataWhereInput | Prisma.LinkMetadataWhereInput[]
  title?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  description?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  image?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  logo?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  author?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  publisher?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  date?: Prisma.DateTimeNullableFilter<"LinkMetadata"> | Date | string | null
  favicon?: Prisma.StringNullableFilter<"LinkMetadata"> | string | null
  scrapedAt?: Prisma.DateTimeFilter<"LinkMetadata"> | Date | string
  url?: Prisma.XOR<Prisma.UrlScalarRelationFilter, Prisma.UrlWhereInput>
}, "id" | "urlId">

export type LinkMetadataOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  logo?: Prisma.SortOrderInput | Prisma.SortOrder
  author?: Prisma.SortOrderInput | Prisma.SortOrder
  publisher?: Prisma.SortOrderInput | Prisma.SortOrder
  date?: Prisma.SortOrderInput | Prisma.SortOrder
  favicon?: Prisma.SortOrderInput | Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
  _count?: Prisma.LinkMetadataCountOrderByAggregateInput
  _max?: Prisma.LinkMetadataMaxOrderByAggregateInput
  _min?: Prisma.LinkMetadataMinOrderByAggregateInput
}

export type LinkMetadataScalarWhereWithAggregatesInput = {
  AND?: Prisma.LinkMetadataScalarWhereWithAggregatesInput | Prisma.LinkMetadataScalarWhereWithAggregatesInput[]
  OR?: Prisma.LinkMetadataScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LinkMetadataScalarWhereWithAggregatesInput | Prisma.LinkMetadataScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LinkMetadata"> | string
  urlId?: Prisma.StringWithAggregatesFilter<"LinkMetadata"> | string
  title?: Prisma.StringNullableWithAggregatesFilter<"LinkMetadata"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"LinkMetadata"> | string | null
  image?: Prisma.StringNullableWithAggregatesFilter<"LinkMetadata"> | string | null
  logo?: Prisma.StringNullableWithAggregatesFilter<"LinkMetadata"> | string | null
  author?: Prisma.StringNullableWithAggregatesFilter<"LinkMetadata"> | string | null
  publisher?: Prisma.StringNullableWithAggregatesFilter<"LinkMetadata"> | string | null
  date?: Prisma.DateTimeNullableWithAggregatesFilter<"LinkMetadata"> | Date | string | null
  favicon?: Prisma.StringNullableWithAggregatesFilter<"LinkMetadata"> | string | null
  scrapedAt?: Prisma.DateTimeWithAggregatesFilter<"LinkMetadata"> | Date | string
}

export type LinkMetadataCreateInput = {
  id?: string
  title?: string | null
  description?: string | null
  image?: string | null
  logo?: string | null
  author?: string | null
  publisher?: string | null
  date?: Date | string | null
  favicon?: string | null
  scrapedAt?: Date | string
  url: Prisma.UrlCreateNestedOneWithoutMetadataInput
}

export type LinkMetadataUncheckedCreateInput = {
  id?: string
  urlId: string
  title?: string | null
  description?: string | null
  image?: string | null
  logo?: string | null
  author?: string | null
  publisher?: string | null
  date?: Date | string | null
  favicon?: string | null
  scrapedAt?: Date | string
}

export type LinkMetadataUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publisher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  favicon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  url?: Prisma.UrlUpdateOneRequiredWithoutMetadataNestedInput
}

export type LinkMetadataUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  urlId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publisher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  favicon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LinkMetadataCreateManyInput = {
  id?: string
  urlId: string
  title?: string | null
  description?: string | null
  image?: string | null
  logo?: string | null
  author?: string | null
  publisher?: string | null
  date?: Date | string | null
  favicon?: string | null
  scrapedAt?: Date | string
}

export type LinkMetadataUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publisher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  favicon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LinkMetadataUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  urlId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publisher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  favicon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LinkMetadataNullableScalarRelationFilter = {
  is?: Prisma.LinkMetadataWhereInput | null
  isNot?: Prisma.LinkMetadataWhereInput | null
}

export type LinkMetadataCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  image?: Prisma.SortOrder
  logo?: Prisma.SortOrder
  author?: Prisma.SortOrder
  publisher?: Prisma.SortOrder
  date?: Prisma.SortOrder
  favicon?: Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
}

export type LinkMetadataMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  image?: Prisma.SortOrder
  logo?: Prisma.SortOrder
  author?: Prisma.SortOrder
  publisher?: Prisma.SortOrder
  date?: Prisma.SortOrder
  favicon?: Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
}

export type LinkMetadataMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  image?: Prisma.SortOrder
  logo?: Prisma.SortOrder
  author?: Prisma.SortOrder
  publisher?: Prisma.SortOrder
  date?: Prisma.SortOrder
  favicon?: Prisma.SortOrder
  scrapedAt?: Prisma.SortOrder
}

export type LinkMetadataCreateNestedOneWithoutUrlInput = {
  create?: Prisma.XOR<Prisma.LinkMetadataCreateWithoutUrlInput, Prisma.LinkMetadataUncheckedCreateWithoutUrlInput>
  connectOrCreate?: Prisma.LinkMetadataCreateOrConnectWithoutUrlInput
  connect?: Prisma.LinkMetadataWhereUniqueInput
}

export type LinkMetadataUncheckedCreateNestedOneWithoutUrlInput = {
  create?: Prisma.XOR<Prisma.LinkMetadataCreateWithoutUrlInput, Prisma.LinkMetadataUncheckedCreateWithoutUrlInput>
  connectOrCreate?: Prisma.LinkMetadataCreateOrConnectWithoutUrlInput
  connect?: Prisma.LinkMetadataWhereUniqueInput
}

export type LinkMetadataUpdateOneWithoutUrlNestedInput = {
  create?: Prisma.XOR<Prisma.LinkMetadataCreateWithoutUrlInput, Prisma.LinkMetadataUncheckedCreateWithoutUrlInput>
  connectOrCreate?: Prisma.LinkMetadataCreateOrConnectWithoutUrlInput
  upsert?: Prisma.LinkMetadataUpsertWithoutUrlInput
  disconnect?: Prisma.LinkMetadataWhereInput | boolean
  delete?: Prisma.LinkMetadataWhereInput | boolean
  connect?: Prisma.LinkMetadataWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LinkMetadataUpdateToOneWithWhereWithoutUrlInput, Prisma.LinkMetadataUpdateWithoutUrlInput>, Prisma.LinkMetadataUncheckedUpdateWithoutUrlInput>
}

export type LinkMetadataUncheckedUpdateOneWithoutUrlNestedInput = {
  create?: Prisma.XOR<Prisma.LinkMetadataCreateWithoutUrlInput, Prisma.LinkMetadataUncheckedCreateWithoutUrlInput>
  connectOrCreate?: Prisma.LinkMetadataCreateOrConnectWithoutUrlInput
  upsert?: Prisma.LinkMetadataUpsertWithoutUrlInput
  disconnect?: Prisma.LinkMetadataWhereInput | boolean
  delete?: Prisma.LinkMetadataWhereInput | boolean
  connect?: Prisma.LinkMetadataWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LinkMetadataUpdateToOneWithWhereWithoutUrlInput, Prisma.LinkMetadataUpdateWithoutUrlInput>, Prisma.LinkMetadataUncheckedUpdateWithoutUrlInput>
}

export type LinkMetadataCreateWithoutUrlInput = {
  id?: string
  title?: string | null
  description?: string | null
  image?: string | null
  logo?: string | null
  author?: string | null
  publisher?: string | null
  date?: Date | string | null
  favicon?: string | null
  scrapedAt?: Date | string
}

export type LinkMetadataUncheckedCreateWithoutUrlInput = {
  id?: string
  title?: string | null
  description?: string | null
  image?: string | null
  logo?: string | null
  author?: string | null
  publisher?: string | null
  date?: Date | string | null
  favicon?: string | null
  scrapedAt?: Date | string
}

export type LinkMetadataCreateOrConnectWithoutUrlInput = {
  where: Prisma.LinkMetadataWhereUniqueInput
  create: Prisma.XOR<Prisma.LinkMetadataCreateWithoutUrlInput, Prisma.LinkMetadataUncheckedCreateWithoutUrlInput>
}

export type LinkMetadataUpsertWithoutUrlInput = {
  update: Prisma.XOR<Prisma.LinkMetadataUpdateWithoutUrlInput, Prisma.LinkMetadataUncheckedUpdateWithoutUrlInput>
  create: Prisma.XOR<Prisma.LinkMetadataCreateWithoutUrlInput, Prisma.LinkMetadataUncheckedCreateWithoutUrlInput>
  where?: Prisma.LinkMetadataWhereInput
}

export type LinkMetadataUpdateToOneWithWhereWithoutUrlInput = {
  where?: Prisma.LinkMetadataWhereInput
  data: Prisma.XOR<Prisma.LinkMetadataUpdateWithoutUrlInput, Prisma.LinkMetadataUncheckedUpdateWithoutUrlInput>
}

export type LinkMetadataUpdateWithoutUrlInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publisher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  favicon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LinkMetadataUncheckedUpdateWithoutUrlInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publisher?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  favicon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type LinkMetadataSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  urlId?: boolean
  title?: boolean
  description?: boolean
  image?: boolean
  logo?: boolean
  author?: boolean
  publisher?: boolean
  date?: boolean
  favicon?: boolean
  scrapedAt?: boolean
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}, ExtArgs["result"]["linkMetadata"]>

export type LinkMetadataSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  urlId?: boolean
  title?: boolean
  description?: boolean
  image?: boolean
  logo?: boolean
  author?: boolean
  publisher?: boolean
  date?: boolean
  favicon?: boolean
  scrapedAt?: boolean
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}, ExtArgs["result"]["linkMetadata"]>

export type LinkMetadataSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  urlId?: boolean
  title?: boolean
  description?: boolean
  image?: boolean
  logo?: boolean
  author?: boolean
  publisher?: boolean
  date?: boolean
  favicon?: boolean
  scrapedAt?: boolean
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}, ExtArgs["result"]["linkMetadata"]>

export type LinkMetadataSelectScalar = {
  id?: boolean
  urlId?: boolean
  title?: boolean
  description?: boolean
  image?: boolean
  logo?: boolean
  author?: boolean
  publisher?: boolean
  date?: boolean
  favicon?: boolean
  scrapedAt?: boolean
}

export type LinkMetadataOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "urlId" | "title" | "description" | "image" | "logo" | "author" | "publisher" | "date" | "favicon" | "scrapedAt", ExtArgs["result"]["linkMetadata"]>
export type LinkMetadataInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}
export type LinkMetadataIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}
export type LinkMetadataIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}

export type $LinkMetadataPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LinkMetadata"
  objects: {
    url: Prisma.$UrlPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    urlId: string
    title: string | null
    description: string | null
    image: string | null
    logo: string | null
    author: string | null
    publisher: string | null
    date: Date | null
    favicon: string | null
    scrapedAt: Date
  }, ExtArgs["result"]["linkMetadata"]>
  composites: {}
}

export type LinkMetadataGetPayload<S extends boolean | null | undefined | LinkMetadataDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LinkMetadataPayload, S>

export type LinkMetadataCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LinkMetadataFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LinkMetadataCountAggregateInputType | true
  }

export interface LinkMetadataDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LinkMetadata'], meta: { name: 'LinkMetadata' } }
  /**
   * Find zero or one LinkMetadata that matches the filter.
   * @param {LinkMetadataFindUniqueArgs} args - Arguments to find a LinkMetadata
   * @example
   * // Get one LinkMetadata
   * const linkMetadata = await prisma.linkMetadata.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LinkMetadataFindUniqueArgs>(args: Prisma.SelectSubset<T, LinkMetadataFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LinkMetadataClient<runtime.Types.Result.GetResult<Prisma.$LinkMetadataPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LinkMetadata that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LinkMetadataFindUniqueOrThrowArgs} args - Arguments to find a LinkMetadata
   * @example
   * // Get one LinkMetadata
   * const linkMetadata = await prisma.linkMetadata.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LinkMetadataFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LinkMetadataFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LinkMetadataClient<runtime.Types.Result.GetResult<Prisma.$LinkMetadataPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LinkMetadata that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkMetadataFindFirstArgs} args - Arguments to find a LinkMetadata
   * @example
   * // Get one LinkMetadata
   * const linkMetadata = await prisma.linkMetadata.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LinkMetadataFindFirstArgs>(args?: Prisma.SelectSubset<T, LinkMetadataFindFirstArgs<ExtArgs>>): Prisma.Prisma__LinkMetadataClient<runtime.Types.Result.GetResult<Prisma.$LinkMetadataPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LinkMetadata that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkMetadataFindFirstOrThrowArgs} args - Arguments to find a LinkMetadata
   * @example
   * // Get one LinkMetadata
   * const linkMetadata = await prisma.linkMetadata.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LinkMetadataFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LinkMetadataFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LinkMetadataClient<runtime.Types.Result.GetResult<Prisma.$LinkMetadataPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LinkMetadata that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkMetadataFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LinkMetadata
   * const linkMetadata = await prisma.linkMetadata.findMany()
   * 
   * // Get first 10 LinkMetadata
   * const linkMetadata = await prisma.linkMetadata.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const linkMetadataWithIdOnly = await prisma.linkMetadata.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LinkMetadataFindManyArgs>(args?: Prisma.SelectSubset<T, LinkMetadataFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LinkMetadataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LinkMetadata.
   * @param {LinkMetadataCreateArgs} args - Arguments to create a LinkMetadata.
   * @example
   * // Create one LinkMetadata
   * const LinkMetadata = await prisma.linkMetadata.create({
   *   data: {
   *     // ... data to create a LinkMetadata
   *   }
   * })
   * 
   */
  create<T extends LinkMetadataCreateArgs>(args: Prisma.SelectSubset<T, LinkMetadataCreateArgs<ExtArgs>>): Prisma.Prisma__LinkMetadataClient<runtime.Types.Result.GetResult<Prisma.$LinkMetadataPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LinkMetadata.
   * @param {LinkMetadataCreateManyArgs} args - Arguments to create many LinkMetadata.
   * @example
   * // Create many LinkMetadata
   * const linkMetadata = await prisma.linkMetadata.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LinkMetadataCreateManyArgs>(args?: Prisma.SelectSubset<T, LinkMetadataCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LinkMetadata and returns the data saved in the database.
   * @param {LinkMetadataCreateManyAndReturnArgs} args - Arguments to create many LinkMetadata.
   * @example
   * // Create many LinkMetadata
   * const linkMetadata = await prisma.linkMetadata.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LinkMetadata and only return the `id`
   * const linkMetadataWithIdOnly = await prisma.linkMetadata.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LinkMetadataCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LinkMetadataCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LinkMetadataPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LinkMetadata.
   * @param {LinkMetadataDeleteArgs} args - Arguments to delete one LinkMetadata.
   * @example
   * // Delete one LinkMetadata
   * const LinkMetadata = await prisma.linkMetadata.delete({
   *   where: {
   *     // ... filter to delete one LinkMetadata
   *   }
   * })
   * 
   */
  delete<T extends LinkMetadataDeleteArgs>(args: Prisma.SelectSubset<T, LinkMetadataDeleteArgs<ExtArgs>>): Prisma.Prisma__LinkMetadataClient<runtime.Types.Result.GetResult<Prisma.$LinkMetadataPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LinkMetadata.
   * @param {LinkMetadataUpdateArgs} args - Arguments to update one LinkMetadata.
   * @example
   * // Update one LinkMetadata
   * const linkMetadata = await prisma.linkMetadata.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LinkMetadataUpdateArgs>(args: Prisma.SelectSubset<T, LinkMetadataUpdateArgs<ExtArgs>>): Prisma.Prisma__LinkMetadataClient<runtime.Types.Result.GetResult<Prisma.$LinkMetadataPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LinkMetadata.
   * @param {LinkMetadataDeleteManyArgs} args - Arguments to filter LinkMetadata to delete.
   * @example
   * // Delete a few LinkMetadata
   * const { count } = await prisma.linkMetadata.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LinkMetadataDeleteManyArgs>(args?: Prisma.SelectSubset<T, LinkMetadataDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LinkMetadata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkMetadataUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LinkMetadata
   * const linkMetadata = await prisma.linkMetadata.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LinkMetadataUpdateManyArgs>(args: Prisma.SelectSubset<T, LinkMetadataUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LinkMetadata and returns the data updated in the database.
   * @param {LinkMetadataUpdateManyAndReturnArgs} args - Arguments to update many LinkMetadata.
   * @example
   * // Update many LinkMetadata
   * const linkMetadata = await prisma.linkMetadata.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LinkMetadata and only return the `id`
   * const linkMetadataWithIdOnly = await prisma.linkMetadata.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LinkMetadataUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LinkMetadataUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LinkMetadataPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LinkMetadata.
   * @param {LinkMetadataUpsertArgs} args - Arguments to update or create a LinkMetadata.
   * @example
   * // Update or create a LinkMetadata
   * const linkMetadata = await prisma.linkMetadata.upsert({
   *   create: {
   *     // ... data to create a LinkMetadata
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LinkMetadata we want to update
   *   }
   * })
   */
  upsert<T extends LinkMetadataUpsertArgs>(args: Prisma.SelectSubset<T, LinkMetadataUpsertArgs<ExtArgs>>): Prisma.Prisma__LinkMetadataClient<runtime.Types.Result.GetResult<Prisma.$LinkMetadataPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LinkMetadata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkMetadataCountArgs} args - Arguments to filter LinkMetadata to count.
   * @example
   * // Count the number of LinkMetadata
   * const count = await prisma.linkMetadata.count({
   *   where: {
   *     // ... the filter for the LinkMetadata we want to count
   *   }
   * })
  **/
  count<T extends LinkMetadataCountArgs>(
    args?: Prisma.Subset<T, LinkMetadataCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LinkMetadataCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LinkMetadata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkMetadataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LinkMetadataAggregateArgs>(args: Prisma.Subset<T, LinkMetadataAggregateArgs>): Prisma.PrismaPromise<GetLinkMetadataAggregateType<T>>

  /**
   * Group by LinkMetadata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkMetadataGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LinkMetadataGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LinkMetadataGroupByArgs['orderBy'] }
      : { orderBy?: LinkMetadataGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LinkMetadataGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLinkMetadataGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LinkMetadata model
 */
readonly fields: LinkMetadataFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LinkMetadata.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LinkMetadataClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  url<T extends Prisma.UrlDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UrlDefaultArgs<ExtArgs>>): Prisma.Prisma__UrlClient<runtime.Types.Result.GetResult<Prisma.$UrlPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LinkMetadata model
 */
export interface LinkMetadataFieldRefs {
  readonly id: Prisma.FieldRef<"LinkMetadata", 'String'>
  readonly urlId: Prisma.FieldRef<"LinkMetadata", 'String'>
  readonly title: Prisma.FieldRef<"LinkMetadata", 'String'>
  readonly description: Prisma.FieldRef<"LinkMetadata", 'String'>
  readonly image: Prisma.FieldRef<"LinkMetadata", 'String'>
  readonly logo: Prisma.FieldRef<"LinkMetadata", 'String'>
  readonly author: Prisma.FieldRef<"LinkMetadata", 'String'>
  readonly publisher: Prisma.FieldRef<"LinkMetadata", 'String'>
  readonly date: Prisma.FieldRef<"LinkMetadata", 'DateTime'>
  readonly favicon: Prisma.FieldRef<"LinkMetadata", 'String'>
  readonly scrapedAt: Prisma.FieldRef<"LinkMetadata", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LinkMetadata findUnique
 */
export type LinkMetadataFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkMetadata
   */
  select?: Prisma.LinkMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkMetadata
   */
  omit?: Prisma.LinkMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkMetadataInclude<ExtArgs> | null
  /**
   * Filter, which LinkMetadata to fetch.
   */
  where: Prisma.LinkMetadataWhereUniqueInput
}

/**
 * LinkMetadata findUniqueOrThrow
 */
export type LinkMetadataFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkMetadata
   */
  select?: Prisma.LinkMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkMetadata
   */
  omit?: Prisma.LinkMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkMetadataInclude<ExtArgs> | null
  /**
   * Filter, which LinkMetadata to fetch.
   */
  where: Prisma.LinkMetadataWhereUniqueInput
}

/**
 * LinkMetadata findFirst
 */
export type LinkMetadataFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkMetadata
   */
  select?: Prisma.LinkMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkMetadata
   */
  omit?: Prisma.LinkMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkMetadataInclude<ExtArgs> | null
  /**
   * Filter, which LinkMetadata to fetch.
   */
  where?: Prisma.LinkMetadataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LinkMetadata to fetch.
   */
  orderBy?: Prisma.LinkMetadataOrderByWithRelationInput | Prisma.LinkMetadataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LinkMetadata.
   */
  cursor?: Prisma.LinkMetadataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LinkMetadata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LinkMetadata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LinkMetadata.
   */
  distinct?: Prisma.LinkMetadataScalarFieldEnum | Prisma.LinkMetadataScalarFieldEnum[]
}

/**
 * LinkMetadata findFirstOrThrow
 */
export type LinkMetadataFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkMetadata
   */
  select?: Prisma.LinkMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkMetadata
   */
  omit?: Prisma.LinkMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkMetadataInclude<ExtArgs> | null
  /**
   * Filter, which LinkMetadata to fetch.
   */
  where?: Prisma.LinkMetadataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LinkMetadata to fetch.
   */
  orderBy?: Prisma.LinkMetadataOrderByWithRelationInput | Prisma.LinkMetadataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LinkMetadata.
   */
  cursor?: Prisma.LinkMetadataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LinkMetadata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LinkMetadata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LinkMetadata.
   */
  distinct?: Prisma.LinkMetadataScalarFieldEnum | Prisma.LinkMetadataScalarFieldEnum[]
}

/**
 * LinkMetadata findMany
 */
export type LinkMetadataFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkMetadata
   */
  select?: Prisma.LinkMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkMetadata
   */
  omit?: Prisma.LinkMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkMetadataInclude<ExtArgs> | null
  /**
   * Filter, which LinkMetadata to fetch.
   */
  where?: Prisma.LinkMetadataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LinkMetadata to fetch.
   */
  orderBy?: Prisma.LinkMetadataOrderByWithRelationInput | Prisma.LinkMetadataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LinkMetadata.
   */
  cursor?: Prisma.LinkMetadataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LinkMetadata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LinkMetadata.
   */
  skip?: number
  distinct?: Prisma.LinkMetadataScalarFieldEnum | Prisma.LinkMetadataScalarFieldEnum[]
}

/**
 * LinkMetadata create
 */
export type LinkMetadataCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkMetadata
   */
  select?: Prisma.LinkMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkMetadata
   */
  omit?: Prisma.LinkMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkMetadataInclude<ExtArgs> | null
  /**
   * The data needed to create a LinkMetadata.
   */
  data: Prisma.XOR<Prisma.LinkMetadataCreateInput, Prisma.LinkMetadataUncheckedCreateInput>
}

/**
 * LinkMetadata createMany
 */
export type LinkMetadataCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LinkMetadata.
   */
  data: Prisma.LinkMetadataCreateManyInput | Prisma.LinkMetadataCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LinkMetadata createManyAndReturn
 */
export type LinkMetadataCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkMetadata
   */
  select?: Prisma.LinkMetadataSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LinkMetadata
   */
  omit?: Prisma.LinkMetadataOmit<ExtArgs> | null
  /**
   * The data used to create many LinkMetadata.
   */
  data: Prisma.LinkMetadataCreateManyInput | Prisma.LinkMetadataCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkMetadataIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LinkMetadata update
 */
export type LinkMetadataUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkMetadata
   */
  select?: Prisma.LinkMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkMetadata
   */
  omit?: Prisma.LinkMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkMetadataInclude<ExtArgs> | null
  /**
   * The data needed to update a LinkMetadata.
   */
  data: Prisma.XOR<Prisma.LinkMetadataUpdateInput, Prisma.LinkMetadataUncheckedUpdateInput>
  /**
   * Choose, which LinkMetadata to update.
   */
  where: Prisma.LinkMetadataWhereUniqueInput
}

/**
 * LinkMetadata updateMany
 */
export type LinkMetadataUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LinkMetadata.
   */
  data: Prisma.XOR<Prisma.LinkMetadataUpdateManyMutationInput, Prisma.LinkMetadataUncheckedUpdateManyInput>
  /**
   * Filter which LinkMetadata to update
   */
  where?: Prisma.LinkMetadataWhereInput
  /**
   * Limit how many LinkMetadata to update.
   */
  limit?: number
}

/**
 * LinkMetadata updateManyAndReturn
 */
export type LinkMetadataUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkMetadata
   */
  select?: Prisma.LinkMetadataSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LinkMetadata
   */
  omit?: Prisma.LinkMetadataOmit<ExtArgs> | null
  /**
   * The data used to update LinkMetadata.
   */
  data: Prisma.XOR<Prisma.LinkMetadataUpdateManyMutationInput, Prisma.LinkMetadataUncheckedUpdateManyInput>
  /**
   * Filter which LinkMetadata to update
   */
  where?: Prisma.LinkMetadataWhereInput
  /**
   * Limit how many LinkMetadata to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkMetadataIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LinkMetadata upsert
 */
export type LinkMetadataUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkMetadata
   */
  select?: Prisma.LinkMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkMetadata
   */
  omit?: Prisma.LinkMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkMetadataInclude<ExtArgs> | null
  /**
   * The filter to search for the LinkMetadata to update in case it exists.
   */
  where: Prisma.LinkMetadataWhereUniqueInput
  /**
   * In case the LinkMetadata found by the `where` argument doesn't exist, create a new LinkMetadata with this data.
   */
  create: Prisma.XOR<Prisma.LinkMetadataCreateInput, Prisma.LinkMetadataUncheckedCreateInput>
  /**
   * In case the LinkMetadata was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LinkMetadataUpdateInput, Prisma.LinkMetadataUncheckedUpdateInput>
}

/**
 * LinkMetadata delete
 */
export type LinkMetadataDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkMetadata
   */
  select?: Prisma.LinkMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkMetadata
   */
  omit?: Prisma.LinkMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkMetadataInclude<ExtArgs> | null
  /**
   * Filter which LinkMetadata to delete.
   */
  where: Prisma.LinkMetadataWhereUniqueInput
}

/**
 * LinkMetadata deleteMany
 */
export type LinkMetadataDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LinkMetadata to delete
   */
  where?: Prisma.LinkMetadataWhereInput
  /**
   * Limit how many LinkMetadata to delete.
   */
  limit?: number
}

/**
 * LinkMetadata without action
 */
export type LinkMetadataDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkMetadata
   */
  select?: Prisma.LinkMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkMetadata
   */
  omit?: Prisma.LinkMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkMetadataInclude<ExtArgs> | null
}
