
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RotationLink` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RotationLink
 * 
 */
export type RotationLinkModel = runtime.Types.Result.DefaultSelection<Prisma.$RotationLinkPayload>

export type AggregateRotationLink = {
  _count: RotationLinkCountAggregateOutputType | null
  _avg: RotationLinkAvgAggregateOutputType | null
  _sum: RotationLinkSumAggregateOutputType | null
  _min: RotationLinkMinAggregateOutputType | null
  _max: RotationLinkMaxAggregateOutputType | null
}

export type RotationLinkAvgAggregateOutputType = {
  weight: number | null
  clicks: number | null
}

export type RotationLinkSumAggregateOutputType = {
  weight: number | null
  clicks: number | null
}

export type RotationLinkMinAggregateOutputType = {
  id: string | null
  urlId: string | null
  destination: string | null
  weight: number | null
  label: string | null
  clicks: number | null
  isActive: boolean | null
  createdAt: Date | null
}

export type RotationLinkMaxAggregateOutputType = {
  id: string | null
  urlId: string | null
  destination: string | null
  weight: number | null
  label: string | null
  clicks: number | null
  isActive: boolean | null
  createdAt: Date | null
}

export type RotationLinkCountAggregateOutputType = {
  id: number
  urlId: number
  destination: number
  weight: number
  label: number
  clicks: number
  isActive: number
  createdAt: number
  _all: number
}


export type RotationLinkAvgAggregateInputType = {
  weight?: true
  clicks?: true
}

export type RotationLinkSumAggregateInputType = {
  weight?: true
  clicks?: true
}

export type RotationLinkMinAggregateInputType = {
  id?: true
  urlId?: true
  destination?: true
  weight?: true
  label?: true
  clicks?: true
  isActive?: true
  createdAt?: true
}

export type RotationLinkMaxAggregateInputType = {
  id?: true
  urlId?: true
  destination?: true
  weight?: true
  label?: true
  clicks?: true
  isActive?: true
  createdAt?: true
}

export type RotationLinkCountAggregateInputType = {
  id?: true
  urlId?: true
  destination?: true
  weight?: true
  label?: true
  clicks?: true
  isActive?: true
  createdAt?: true
  _all?: true
}

export type RotationLinkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RotationLink to aggregate.
   */
  where?: Prisma.RotationLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RotationLinks to fetch.
   */
  orderBy?: Prisma.RotationLinkOrderByWithRelationInput | Prisma.RotationLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RotationLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RotationLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RotationLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RotationLinks
  **/
  _count?: true | RotationLinkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RotationLinkAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RotationLinkSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RotationLinkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RotationLinkMaxAggregateInputType
}

export type GetRotationLinkAggregateType<T extends RotationLinkAggregateArgs> = {
      [P in keyof T & keyof AggregateRotationLink]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRotationLink[P]>
    : Prisma.GetScalarType<T[P], AggregateRotationLink[P]>
}




export type RotationLinkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RotationLinkWhereInput
  orderBy?: Prisma.RotationLinkOrderByWithAggregationInput | Prisma.RotationLinkOrderByWithAggregationInput[]
  by: Prisma.RotationLinkScalarFieldEnum[] | Prisma.RotationLinkScalarFieldEnum
  having?: Prisma.RotationLinkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RotationLinkCountAggregateInputType | true
  _avg?: RotationLinkAvgAggregateInputType
  _sum?: RotationLinkSumAggregateInputType
  _min?: RotationLinkMinAggregateInputType
  _max?: RotationLinkMaxAggregateInputType
}

export type RotationLinkGroupByOutputType = {
  id: string
  urlId: string
  destination: string
  weight: number
  label: string | null
  clicks: number
  isActive: boolean
  createdAt: Date
  _count: RotationLinkCountAggregateOutputType | null
  _avg: RotationLinkAvgAggregateOutputType | null
  _sum: RotationLinkSumAggregateOutputType | null
  _min: RotationLinkMinAggregateOutputType | null
  _max: RotationLinkMaxAggregateOutputType | null
}

type GetRotationLinkGroupByPayload<T extends RotationLinkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RotationLinkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RotationLinkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RotationLinkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RotationLinkGroupByOutputType[P]>
      }
    >
  >



export type RotationLinkWhereInput = {
  AND?: Prisma.RotationLinkWhereInput | Prisma.RotationLinkWhereInput[]
  OR?: Prisma.RotationLinkWhereInput[]
  NOT?: Prisma.RotationLinkWhereInput | Prisma.RotationLinkWhereInput[]
  id?: Prisma.StringFilter<"RotationLink"> | string
  urlId?: Prisma.StringFilter<"RotationLink"> | string
  destination?: Prisma.StringFilter<"RotationLink"> | string
  weight?: Prisma.IntFilter<"RotationLink"> | number
  label?: Prisma.StringNullableFilter<"RotationLink"> | string | null
  clicks?: Prisma.IntFilter<"RotationLink"> | number
  isActive?: Prisma.BoolFilter<"RotationLink"> | boolean
  createdAt?: Prisma.DateTimeFilter<"RotationLink"> | Date | string
  url?: Prisma.XOR<Prisma.UrlScalarRelationFilter, Prisma.UrlWhereInput>
}

export type RotationLinkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  label?: Prisma.SortOrderInput | Prisma.SortOrder
  clicks?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  url?: Prisma.UrlOrderByWithRelationInput
}

export type RotationLinkWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RotationLinkWhereInput | Prisma.RotationLinkWhereInput[]
  OR?: Prisma.RotationLinkWhereInput[]
  NOT?: Prisma.RotationLinkWhereInput | Prisma.RotationLinkWhereInput[]
  urlId?: Prisma.StringFilter<"RotationLink"> | string
  destination?: Prisma.StringFilter<"RotationLink"> | string
  weight?: Prisma.IntFilter<"RotationLink"> | number
  label?: Prisma.StringNullableFilter<"RotationLink"> | string | null
  clicks?: Prisma.IntFilter<"RotationLink"> | number
  isActive?: Prisma.BoolFilter<"RotationLink"> | boolean
  createdAt?: Prisma.DateTimeFilter<"RotationLink"> | Date | string
  url?: Prisma.XOR<Prisma.UrlScalarRelationFilter, Prisma.UrlWhereInput>
}, "id">

export type RotationLinkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  label?: Prisma.SortOrderInput | Prisma.SortOrder
  clicks?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.RotationLinkCountOrderByAggregateInput
  _avg?: Prisma.RotationLinkAvgOrderByAggregateInput
  _max?: Prisma.RotationLinkMaxOrderByAggregateInput
  _min?: Prisma.RotationLinkMinOrderByAggregateInput
  _sum?: Prisma.RotationLinkSumOrderByAggregateInput
}

export type RotationLinkScalarWhereWithAggregatesInput = {
  AND?: Prisma.RotationLinkScalarWhereWithAggregatesInput | Prisma.RotationLinkScalarWhereWithAggregatesInput[]
  OR?: Prisma.RotationLinkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RotationLinkScalarWhereWithAggregatesInput | Prisma.RotationLinkScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RotationLink"> | string
  urlId?: Prisma.StringWithAggregatesFilter<"RotationLink"> | string
  destination?: Prisma.StringWithAggregatesFilter<"RotationLink"> | string
  weight?: Prisma.IntWithAggregatesFilter<"RotationLink"> | number
  label?: Prisma.StringNullableWithAggregatesFilter<"RotationLink"> | string | null
  clicks?: Prisma.IntWithAggregatesFilter<"RotationLink"> | number
  isActive?: Prisma.BoolWithAggregatesFilter<"RotationLink"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RotationLink"> | Date | string
}

export type RotationLinkCreateInput = {
  id?: string
  destination: string
  weight?: number
  label?: string | null
  clicks?: number
  isActive?: boolean
  createdAt?: Date | string
  url: Prisma.UrlCreateNestedOneWithoutRotationLinksInput
}

export type RotationLinkUncheckedCreateInput = {
  id?: string
  urlId: string
  destination: string
  weight?: number
  label?: string | null
  clicks?: number
  isActive?: boolean
  createdAt?: Date | string
}

export type RotationLinkUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clicks?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  url?: Prisma.UrlUpdateOneRequiredWithoutRotationLinksNestedInput
}

export type RotationLinkUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  urlId?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clicks?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RotationLinkCreateManyInput = {
  id?: string
  urlId: string
  destination: string
  weight?: number
  label?: string | null
  clicks?: number
  isActive?: boolean
  createdAt?: Date | string
}

export type RotationLinkUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clicks?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RotationLinkUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  urlId?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clicks?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RotationLinkListRelationFilter = {
  every?: Prisma.RotationLinkWhereInput
  some?: Prisma.RotationLinkWhereInput
  none?: Prisma.RotationLinkWhereInput
}

export type RotationLinkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RotationLinkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  label?: Prisma.SortOrder
  clicks?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RotationLinkAvgOrderByAggregateInput = {
  weight?: Prisma.SortOrder
  clicks?: Prisma.SortOrder
}

export type RotationLinkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  label?: Prisma.SortOrder
  clicks?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RotationLinkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  label?: Prisma.SortOrder
  clicks?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RotationLinkSumOrderByAggregateInput = {
  weight?: Prisma.SortOrder
  clicks?: Prisma.SortOrder
}

export type RotationLinkCreateNestedManyWithoutUrlInput = {
  create?: Prisma.XOR<Prisma.RotationLinkCreateWithoutUrlInput, Prisma.RotationLinkUncheckedCreateWithoutUrlInput> | Prisma.RotationLinkCreateWithoutUrlInput[] | Prisma.RotationLinkUncheckedCreateWithoutUrlInput[]
  connectOrCreate?: Prisma.RotationLinkCreateOrConnectWithoutUrlInput | Prisma.RotationLinkCreateOrConnectWithoutUrlInput[]
  createMany?: Prisma.RotationLinkCreateManyUrlInputEnvelope
  connect?: Prisma.RotationLinkWhereUniqueInput | Prisma.RotationLinkWhereUniqueInput[]
}

export type RotationLinkUncheckedCreateNestedManyWithoutUrlInput = {
  create?: Prisma.XOR<Prisma.RotationLinkCreateWithoutUrlInput, Prisma.RotationLinkUncheckedCreateWithoutUrlInput> | Prisma.RotationLinkCreateWithoutUrlInput[] | Prisma.RotationLinkUncheckedCreateWithoutUrlInput[]
  connectOrCreate?: Prisma.RotationLinkCreateOrConnectWithoutUrlInput | Prisma.RotationLinkCreateOrConnectWithoutUrlInput[]
  createMany?: Prisma.RotationLinkCreateManyUrlInputEnvelope
  connect?: Prisma.RotationLinkWhereUniqueInput | Prisma.RotationLinkWhereUniqueInput[]
}

export type RotationLinkUpdateManyWithoutUrlNestedInput = {
  create?: Prisma.XOR<Prisma.RotationLinkCreateWithoutUrlInput, Prisma.RotationLinkUncheckedCreateWithoutUrlInput> | Prisma.RotationLinkCreateWithoutUrlInput[] | Prisma.RotationLinkUncheckedCreateWithoutUrlInput[]
  connectOrCreate?: Prisma.RotationLinkCreateOrConnectWithoutUrlInput | Prisma.RotationLinkCreateOrConnectWithoutUrlInput[]
  upsert?: Prisma.RotationLinkUpsertWithWhereUniqueWithoutUrlInput | Prisma.RotationLinkUpsertWithWhereUniqueWithoutUrlInput[]
  createMany?: Prisma.RotationLinkCreateManyUrlInputEnvelope
  set?: Prisma.RotationLinkWhereUniqueInput | Prisma.RotationLinkWhereUniqueInput[]
  disconnect?: Prisma.RotationLinkWhereUniqueInput | Prisma.RotationLinkWhereUniqueInput[]
  delete?: Prisma.RotationLinkWhereUniqueInput | Prisma.RotationLinkWhereUniqueInput[]
  connect?: Prisma.RotationLinkWhereUniqueInput | Prisma.RotationLinkWhereUniqueInput[]
  update?: Prisma.RotationLinkUpdateWithWhereUniqueWithoutUrlInput | Prisma.RotationLinkUpdateWithWhereUniqueWithoutUrlInput[]
  updateMany?: Prisma.RotationLinkUpdateManyWithWhereWithoutUrlInput | Prisma.RotationLinkUpdateManyWithWhereWithoutUrlInput[]
  deleteMany?: Prisma.RotationLinkScalarWhereInput | Prisma.RotationLinkScalarWhereInput[]
}

export type RotationLinkUncheckedUpdateManyWithoutUrlNestedInput = {
  create?: Prisma.XOR<Prisma.RotationLinkCreateWithoutUrlInput, Prisma.RotationLinkUncheckedCreateWithoutUrlInput> | Prisma.RotationLinkCreateWithoutUrlInput[] | Prisma.RotationLinkUncheckedCreateWithoutUrlInput[]
  connectOrCreate?: Prisma.RotationLinkCreateOrConnectWithoutUrlInput | Prisma.RotationLinkCreateOrConnectWithoutUrlInput[]
  upsert?: Prisma.RotationLinkUpsertWithWhereUniqueWithoutUrlInput | Prisma.RotationLinkUpsertWithWhereUniqueWithoutUrlInput[]
  createMany?: Prisma.RotationLinkCreateManyUrlInputEnvelope
  set?: Prisma.RotationLinkWhereUniqueInput | Prisma.RotationLinkWhereUniqueInput[]
  disconnect?: Prisma.RotationLinkWhereUniqueInput | Prisma.RotationLinkWhereUniqueInput[]
  delete?: Prisma.RotationLinkWhereUniqueInput | Prisma.RotationLinkWhereUniqueInput[]
  connect?: Prisma.RotationLinkWhereUniqueInput | Prisma.RotationLinkWhereUniqueInput[]
  update?: Prisma.RotationLinkUpdateWithWhereUniqueWithoutUrlInput | Prisma.RotationLinkUpdateWithWhereUniqueWithoutUrlInput[]
  updateMany?: Prisma.RotationLinkUpdateManyWithWhereWithoutUrlInput | Prisma.RotationLinkUpdateManyWithWhereWithoutUrlInput[]
  deleteMany?: Prisma.RotationLinkScalarWhereInput | Prisma.RotationLinkScalarWhereInput[]
}

export type RotationLinkCreateWithoutUrlInput = {
  id?: string
  destination: string
  weight?: number
  label?: string | null
  clicks?: number
  isActive?: boolean
  createdAt?: Date | string
}

export type RotationLinkUncheckedCreateWithoutUrlInput = {
  id?: string
  destination: string
  weight?: number
  label?: string | null
  clicks?: number
  isActive?: boolean
  createdAt?: Date | string
}

export type RotationLinkCreateOrConnectWithoutUrlInput = {
  where: Prisma.RotationLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.RotationLinkCreateWithoutUrlInput, Prisma.RotationLinkUncheckedCreateWithoutUrlInput>
}

export type RotationLinkCreateManyUrlInputEnvelope = {
  data: Prisma.RotationLinkCreateManyUrlInput | Prisma.RotationLinkCreateManyUrlInput[]
  skipDuplicates?: boolean
}

export type RotationLinkUpsertWithWhereUniqueWithoutUrlInput = {
  where: Prisma.RotationLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.RotationLinkUpdateWithoutUrlInput, Prisma.RotationLinkUncheckedUpdateWithoutUrlInput>
  create: Prisma.XOR<Prisma.RotationLinkCreateWithoutUrlInput, Prisma.RotationLinkUncheckedCreateWithoutUrlInput>
}

export type RotationLinkUpdateWithWhereUniqueWithoutUrlInput = {
  where: Prisma.RotationLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.RotationLinkUpdateWithoutUrlInput, Prisma.RotationLinkUncheckedUpdateWithoutUrlInput>
}

export type RotationLinkUpdateManyWithWhereWithoutUrlInput = {
  where: Prisma.RotationLinkScalarWhereInput
  data: Prisma.XOR<Prisma.RotationLinkUpdateManyMutationInput, Prisma.RotationLinkUncheckedUpdateManyWithoutUrlInput>
}

export type RotationLinkScalarWhereInput = {
  AND?: Prisma.RotationLinkScalarWhereInput | Prisma.RotationLinkScalarWhereInput[]
  OR?: Prisma.RotationLinkScalarWhereInput[]
  NOT?: Prisma.RotationLinkScalarWhereInput | Prisma.RotationLinkScalarWhereInput[]
  id?: Prisma.StringFilter<"RotationLink"> | string
  urlId?: Prisma.StringFilter<"RotationLink"> | string
  destination?: Prisma.StringFilter<"RotationLink"> | string
  weight?: Prisma.IntFilter<"RotationLink"> | number
  label?: Prisma.StringNullableFilter<"RotationLink"> | string | null
  clicks?: Prisma.IntFilter<"RotationLink"> | number
  isActive?: Prisma.BoolFilter<"RotationLink"> | boolean
  createdAt?: Prisma.DateTimeFilter<"RotationLink"> | Date | string
}

export type RotationLinkCreateManyUrlInput = {
  id?: string
  destination: string
  weight?: number
  label?: string | null
  clicks?: number
  isActive?: boolean
  createdAt?: Date | string
}

export type RotationLinkUpdateWithoutUrlInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clicks?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RotationLinkUncheckedUpdateWithoutUrlInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clicks?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RotationLinkUncheckedUpdateManyWithoutUrlInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  destination?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clicks?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RotationLinkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  urlId?: boolean
  destination?: boolean
  weight?: boolean
  label?: boolean
  clicks?: boolean
  isActive?: boolean
  createdAt?: boolean
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rotationLink"]>

export type RotationLinkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  urlId?: boolean
  destination?: boolean
  weight?: boolean
  label?: boolean
  clicks?: boolean
  isActive?: boolean
  createdAt?: boolean
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rotationLink"]>

export type RotationLinkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  urlId?: boolean
  destination?: boolean
  weight?: boolean
  label?: boolean
  clicks?: boolean
  isActive?: boolean
  createdAt?: boolean
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rotationLink"]>

export type RotationLinkSelectScalar = {
  id?: boolean
  urlId?: boolean
  destination?: boolean
  weight?: boolean
  label?: boolean
  clicks?: boolean
  isActive?: boolean
  createdAt?: boolean
}

export type RotationLinkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "urlId" | "destination" | "weight" | "label" | "clicks" | "isActive" | "createdAt", ExtArgs["result"]["rotationLink"]>
export type RotationLinkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}
export type RotationLinkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}
export type RotationLinkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}

export type $RotationLinkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RotationLink"
  objects: {
    url: Prisma.$UrlPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    urlId: string
    destination: string
    weight: number
    label: string | null
    clicks: number
    isActive: boolean
    createdAt: Date
  }, ExtArgs["result"]["rotationLink"]>
  composites: {}
}

export type RotationLinkGetPayload<S extends boolean | null | undefined | RotationLinkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RotationLinkPayload, S>

export type RotationLinkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RotationLinkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RotationLinkCountAggregateInputType | true
  }

export interface RotationLinkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RotationLink'], meta: { name: 'RotationLink' } }
  /**
   * Find zero or one RotationLink that matches the filter.
   * @param {RotationLinkFindUniqueArgs} args - Arguments to find a RotationLink
   * @example
   * // Get one RotationLink
   * const rotationLink = await prisma.rotationLink.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RotationLinkFindUniqueArgs>(args: Prisma.SelectSubset<T, RotationLinkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RotationLinkClient<runtime.Types.Result.GetResult<Prisma.$RotationLinkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RotationLink that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RotationLinkFindUniqueOrThrowArgs} args - Arguments to find a RotationLink
   * @example
   * // Get one RotationLink
   * const rotationLink = await prisma.rotationLink.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RotationLinkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RotationLinkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RotationLinkClient<runtime.Types.Result.GetResult<Prisma.$RotationLinkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RotationLink that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RotationLinkFindFirstArgs} args - Arguments to find a RotationLink
   * @example
   * // Get one RotationLink
   * const rotationLink = await prisma.rotationLink.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RotationLinkFindFirstArgs>(args?: Prisma.SelectSubset<T, RotationLinkFindFirstArgs<ExtArgs>>): Prisma.Prisma__RotationLinkClient<runtime.Types.Result.GetResult<Prisma.$RotationLinkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RotationLink that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RotationLinkFindFirstOrThrowArgs} args - Arguments to find a RotationLink
   * @example
   * // Get one RotationLink
   * const rotationLink = await prisma.rotationLink.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RotationLinkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RotationLinkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RotationLinkClient<runtime.Types.Result.GetResult<Prisma.$RotationLinkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RotationLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RotationLinkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RotationLinks
   * const rotationLinks = await prisma.rotationLink.findMany()
   * 
   * // Get first 10 RotationLinks
   * const rotationLinks = await prisma.rotationLink.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const rotationLinkWithIdOnly = await prisma.rotationLink.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RotationLinkFindManyArgs>(args?: Prisma.SelectSubset<T, RotationLinkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RotationLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RotationLink.
   * @param {RotationLinkCreateArgs} args - Arguments to create a RotationLink.
   * @example
   * // Create one RotationLink
   * const RotationLink = await prisma.rotationLink.create({
   *   data: {
   *     // ... data to create a RotationLink
   *   }
   * })
   * 
   */
  create<T extends RotationLinkCreateArgs>(args: Prisma.SelectSubset<T, RotationLinkCreateArgs<ExtArgs>>): Prisma.Prisma__RotationLinkClient<runtime.Types.Result.GetResult<Prisma.$RotationLinkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RotationLinks.
   * @param {RotationLinkCreateManyArgs} args - Arguments to create many RotationLinks.
   * @example
   * // Create many RotationLinks
   * const rotationLink = await prisma.rotationLink.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RotationLinkCreateManyArgs>(args?: Prisma.SelectSubset<T, RotationLinkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RotationLinks and returns the data saved in the database.
   * @param {RotationLinkCreateManyAndReturnArgs} args - Arguments to create many RotationLinks.
   * @example
   * // Create many RotationLinks
   * const rotationLink = await prisma.rotationLink.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RotationLinks and only return the `id`
   * const rotationLinkWithIdOnly = await prisma.rotationLink.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RotationLinkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RotationLinkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RotationLinkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RotationLink.
   * @param {RotationLinkDeleteArgs} args - Arguments to delete one RotationLink.
   * @example
   * // Delete one RotationLink
   * const RotationLink = await prisma.rotationLink.delete({
   *   where: {
   *     // ... filter to delete one RotationLink
   *   }
   * })
   * 
   */
  delete<T extends RotationLinkDeleteArgs>(args: Prisma.SelectSubset<T, RotationLinkDeleteArgs<ExtArgs>>): Prisma.Prisma__RotationLinkClient<runtime.Types.Result.GetResult<Prisma.$RotationLinkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RotationLink.
   * @param {RotationLinkUpdateArgs} args - Arguments to update one RotationLink.
   * @example
   * // Update one RotationLink
   * const rotationLink = await prisma.rotationLink.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RotationLinkUpdateArgs>(args: Prisma.SelectSubset<T, RotationLinkUpdateArgs<ExtArgs>>): Prisma.Prisma__RotationLinkClient<runtime.Types.Result.GetResult<Prisma.$RotationLinkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RotationLinks.
   * @param {RotationLinkDeleteManyArgs} args - Arguments to filter RotationLinks to delete.
   * @example
   * // Delete a few RotationLinks
   * const { count } = await prisma.rotationLink.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RotationLinkDeleteManyArgs>(args?: Prisma.SelectSubset<T, RotationLinkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RotationLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RotationLinkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RotationLinks
   * const rotationLink = await prisma.rotationLink.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RotationLinkUpdateManyArgs>(args: Prisma.SelectSubset<T, RotationLinkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RotationLinks and returns the data updated in the database.
   * @param {RotationLinkUpdateManyAndReturnArgs} args - Arguments to update many RotationLinks.
   * @example
   * // Update many RotationLinks
   * const rotationLink = await prisma.rotationLink.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RotationLinks and only return the `id`
   * const rotationLinkWithIdOnly = await prisma.rotationLink.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RotationLinkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RotationLinkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RotationLinkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RotationLink.
   * @param {RotationLinkUpsertArgs} args - Arguments to update or create a RotationLink.
   * @example
   * // Update or create a RotationLink
   * const rotationLink = await prisma.rotationLink.upsert({
   *   create: {
   *     // ... data to create a RotationLink
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RotationLink we want to update
   *   }
   * })
   */
  upsert<T extends RotationLinkUpsertArgs>(args: Prisma.SelectSubset<T, RotationLinkUpsertArgs<ExtArgs>>): Prisma.Prisma__RotationLinkClient<runtime.Types.Result.GetResult<Prisma.$RotationLinkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RotationLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RotationLinkCountArgs} args - Arguments to filter RotationLinks to count.
   * @example
   * // Count the number of RotationLinks
   * const count = await prisma.rotationLink.count({
   *   where: {
   *     // ... the filter for the RotationLinks we want to count
   *   }
   * })
  **/
  count<T extends RotationLinkCountArgs>(
    args?: Prisma.Subset<T, RotationLinkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RotationLinkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RotationLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RotationLinkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RotationLinkAggregateArgs>(args: Prisma.Subset<T, RotationLinkAggregateArgs>): Prisma.PrismaPromise<GetRotationLinkAggregateType<T>>

  /**
   * Group by RotationLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RotationLinkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RotationLinkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RotationLinkGroupByArgs['orderBy'] }
      : { orderBy?: RotationLinkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RotationLinkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRotationLinkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RotationLink model
 */
readonly fields: RotationLinkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RotationLink.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RotationLinkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  url<T extends Prisma.UrlDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UrlDefaultArgs<ExtArgs>>): Prisma.Prisma__UrlClient<runtime.Types.Result.GetResult<Prisma.$UrlPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RotationLink model
 */
export interface RotationLinkFieldRefs {
  readonly id: Prisma.FieldRef<"RotationLink", 'String'>
  readonly urlId: Prisma.FieldRef<"RotationLink", 'String'>
  readonly destination: Prisma.FieldRef<"RotationLink", 'String'>
  readonly weight: Prisma.FieldRef<"RotationLink", 'Int'>
  readonly label: Prisma.FieldRef<"RotationLink", 'String'>
  readonly clicks: Prisma.FieldRef<"RotationLink", 'Int'>
  readonly isActive: Prisma.FieldRef<"RotationLink", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"RotationLink", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RotationLink findUnique
 */
export type RotationLinkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RotationLink
   */
  select?: Prisma.RotationLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RotationLink
   */
  omit?: Prisma.RotationLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RotationLinkInclude<ExtArgs> | null
  /**
   * Filter, which RotationLink to fetch.
   */
  where: Prisma.RotationLinkWhereUniqueInput
}

/**
 * RotationLink findUniqueOrThrow
 */
export type RotationLinkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RotationLink
   */
  select?: Prisma.RotationLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RotationLink
   */
  omit?: Prisma.RotationLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RotationLinkInclude<ExtArgs> | null
  /**
   * Filter, which RotationLink to fetch.
   */
  where: Prisma.RotationLinkWhereUniqueInput
}

/**
 * RotationLink findFirst
 */
export type RotationLinkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RotationLink
   */
  select?: Prisma.RotationLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RotationLink
   */
  omit?: Prisma.RotationLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RotationLinkInclude<ExtArgs> | null
  /**
   * Filter, which RotationLink to fetch.
   */
  where?: Prisma.RotationLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RotationLinks to fetch.
   */
  orderBy?: Prisma.RotationLinkOrderByWithRelationInput | Prisma.RotationLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RotationLinks.
   */
  cursor?: Prisma.RotationLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RotationLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RotationLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RotationLinks.
   */
  distinct?: Prisma.RotationLinkScalarFieldEnum | Prisma.RotationLinkScalarFieldEnum[]
}

/**
 * RotationLink findFirstOrThrow
 */
export type RotationLinkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RotationLink
   */
  select?: Prisma.RotationLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RotationLink
   */
  omit?: Prisma.RotationLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RotationLinkInclude<ExtArgs> | null
  /**
   * Filter, which RotationLink to fetch.
   */
  where?: Prisma.RotationLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RotationLinks to fetch.
   */
  orderBy?: Prisma.RotationLinkOrderByWithRelationInput | Prisma.RotationLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RotationLinks.
   */
  cursor?: Prisma.RotationLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RotationLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RotationLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RotationLinks.
   */
  distinct?: Prisma.RotationLinkScalarFieldEnum | Prisma.RotationLinkScalarFieldEnum[]
}

/**
 * RotationLink findMany
 */
export type RotationLinkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RotationLink
   */
  select?: Prisma.RotationLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RotationLink
   */
  omit?: Prisma.RotationLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RotationLinkInclude<ExtArgs> | null
  /**
   * Filter, which RotationLinks to fetch.
   */
  where?: Prisma.RotationLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RotationLinks to fetch.
   */
  orderBy?: Prisma.RotationLinkOrderByWithRelationInput | Prisma.RotationLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RotationLinks.
   */
  cursor?: Prisma.RotationLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RotationLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RotationLinks.
   */
  skip?: number
  distinct?: Prisma.RotationLinkScalarFieldEnum | Prisma.RotationLinkScalarFieldEnum[]
}

/**
 * RotationLink create
 */
export type RotationLinkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RotationLink
   */
  select?: Prisma.RotationLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RotationLink
   */
  omit?: Prisma.RotationLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RotationLinkInclude<ExtArgs> | null
  /**
   * The data needed to create a RotationLink.
   */
  data: Prisma.XOR<Prisma.RotationLinkCreateInput, Prisma.RotationLinkUncheckedCreateInput>
}

/**
 * RotationLink createMany
 */
export type RotationLinkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RotationLinks.
   */
  data: Prisma.RotationLinkCreateManyInput | Prisma.RotationLinkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RotationLink createManyAndReturn
 */
export type RotationLinkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RotationLink
   */
  select?: Prisma.RotationLinkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RotationLink
   */
  omit?: Prisma.RotationLinkOmit<ExtArgs> | null
  /**
   * The data used to create many RotationLinks.
   */
  data: Prisma.RotationLinkCreateManyInput | Prisma.RotationLinkCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RotationLinkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RotationLink update
 */
export type RotationLinkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RotationLink
   */
  select?: Prisma.RotationLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RotationLink
   */
  omit?: Prisma.RotationLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RotationLinkInclude<ExtArgs> | null
  /**
   * The data needed to update a RotationLink.
   */
  data: Prisma.XOR<Prisma.RotationLinkUpdateInput, Prisma.RotationLinkUncheckedUpdateInput>
  /**
   * Choose, which RotationLink to update.
   */
  where: Prisma.RotationLinkWhereUniqueInput
}

/**
 * RotationLink updateMany
 */
export type RotationLinkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RotationLinks.
   */
  data: Prisma.XOR<Prisma.RotationLinkUpdateManyMutationInput, Prisma.RotationLinkUncheckedUpdateManyInput>
  /**
   * Filter which RotationLinks to update
   */
  where?: Prisma.RotationLinkWhereInput
  /**
   * Limit how many RotationLinks to update.
   */
  limit?: number
}

/**
 * RotationLink updateManyAndReturn
 */
export type RotationLinkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RotationLink
   */
  select?: Prisma.RotationLinkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RotationLink
   */
  omit?: Prisma.RotationLinkOmit<ExtArgs> | null
  /**
   * The data used to update RotationLinks.
   */
  data: Prisma.XOR<Prisma.RotationLinkUpdateManyMutationInput, Prisma.RotationLinkUncheckedUpdateManyInput>
  /**
   * Filter which RotationLinks to update
   */
  where?: Prisma.RotationLinkWhereInput
  /**
   * Limit how many RotationLinks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RotationLinkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RotationLink upsert
 */
export type RotationLinkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RotationLink
   */
  select?: Prisma.RotationLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RotationLink
   */
  omit?: Prisma.RotationLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RotationLinkInclude<ExtArgs> | null
  /**
   * The filter to search for the RotationLink to update in case it exists.
   */
  where: Prisma.RotationLinkWhereUniqueInput
  /**
   * In case the RotationLink found by the `where` argument doesn't exist, create a new RotationLink with this data.
   */
  create: Prisma.XOR<Prisma.RotationLinkCreateInput, Prisma.RotationLinkUncheckedCreateInput>
  /**
   * In case the RotationLink was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RotationLinkUpdateInput, Prisma.RotationLinkUncheckedUpdateInput>
}

/**
 * RotationLink delete
 */
export type RotationLinkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RotationLink
   */
  select?: Prisma.RotationLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RotationLink
   */
  omit?: Prisma.RotationLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RotationLinkInclude<ExtArgs> | null
  /**
   * Filter which RotationLink to delete.
   */
  where: Prisma.RotationLinkWhereUniqueInput
}

/**
 * RotationLink deleteMany
 */
export type RotationLinkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RotationLinks to delete
   */
  where?: Prisma.RotationLinkWhereInput
  /**
   * Limit how many RotationLinks to delete.
   */
  limit?: number
}

/**
 * RotationLink without action
 */
export type RotationLinkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RotationLink
   */
  select?: Prisma.RotationLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RotationLink
   */
  omit?: Prisma.RotationLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RotationLinkInclude<ExtArgs> | null
}
