
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserUrl` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserUrl
 * 
 */
export type UserUrlModel = runtime.Types.Result.DefaultSelection<Prisma.$UserUrlPayload>

export type AggregateUserUrl = {
  _count: UserUrlCountAggregateOutputType | null
  _min: UserUrlMinAggregateOutputType | null
  _max: UserUrlMaxAggregateOutputType | null
}

export type UserUrlMinAggregateOutputType = {
  id: string | null
  userId: string | null
  urlId: string | null
  createdAt: Date | null
}

export type UserUrlMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  urlId: string | null
  createdAt: Date | null
}

export type UserUrlCountAggregateOutputType = {
  id: number
  userId: number
  urlId: number
  createdAt: number
  _all: number
}


export type UserUrlMinAggregateInputType = {
  id?: true
  userId?: true
  urlId?: true
  createdAt?: true
}

export type UserUrlMaxAggregateInputType = {
  id?: true
  userId?: true
  urlId?: true
  createdAt?: true
}

export type UserUrlCountAggregateInputType = {
  id?: true
  userId?: true
  urlId?: true
  createdAt?: true
  _all?: true
}

export type UserUrlAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserUrl to aggregate.
   */
  where?: Prisma.UserUrlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserUrls to fetch.
   */
  orderBy?: Prisma.UserUrlOrderByWithRelationInput | Prisma.UserUrlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserUrlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserUrls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserUrls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserUrls
  **/
  _count?: true | UserUrlCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserUrlMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserUrlMaxAggregateInputType
}

export type GetUserUrlAggregateType<T extends UserUrlAggregateArgs> = {
      [P in keyof T & keyof AggregateUserUrl]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserUrl[P]>
    : Prisma.GetScalarType<T[P], AggregateUserUrl[P]>
}




export type UserUrlGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserUrlWhereInput
  orderBy?: Prisma.UserUrlOrderByWithAggregationInput | Prisma.UserUrlOrderByWithAggregationInput[]
  by: Prisma.UserUrlScalarFieldEnum[] | Prisma.UserUrlScalarFieldEnum
  having?: Prisma.UserUrlScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserUrlCountAggregateInputType | true
  _min?: UserUrlMinAggregateInputType
  _max?: UserUrlMaxAggregateInputType
}

export type UserUrlGroupByOutputType = {
  id: string
  userId: string
  urlId: string
  createdAt: Date
  _count: UserUrlCountAggregateOutputType | null
  _min: UserUrlMinAggregateOutputType | null
  _max: UserUrlMaxAggregateOutputType | null
}

type GetUserUrlGroupByPayload<T extends UserUrlGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserUrlGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserUrlGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserUrlGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserUrlGroupByOutputType[P]>
      }
    >
  >



export type UserUrlWhereInput = {
  AND?: Prisma.UserUrlWhereInput | Prisma.UserUrlWhereInput[]
  OR?: Prisma.UserUrlWhereInput[]
  NOT?: Prisma.UserUrlWhereInput | Prisma.UserUrlWhereInput[]
  id?: Prisma.StringFilter<"UserUrl"> | string
  userId?: Prisma.StringFilter<"UserUrl"> | string
  urlId?: Prisma.StringFilter<"UserUrl"> | string
  createdAt?: Prisma.DateTimeFilter<"UserUrl"> | Date | string
  url?: Prisma.XOR<Prisma.UrlScalarRelationFilter, Prisma.UrlWhereInput>
}

export type UserUrlOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  url?: Prisma.UrlOrderByWithRelationInput
}

export type UserUrlWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_urlId?: Prisma.UserUrlUserIdUrlIdCompoundUniqueInput
  AND?: Prisma.UserUrlWhereInput | Prisma.UserUrlWhereInput[]
  OR?: Prisma.UserUrlWhereInput[]
  NOT?: Prisma.UserUrlWhereInput | Prisma.UserUrlWhereInput[]
  userId?: Prisma.StringFilter<"UserUrl"> | string
  urlId?: Prisma.StringFilter<"UserUrl"> | string
  createdAt?: Prisma.DateTimeFilter<"UserUrl"> | Date | string
  url?: Prisma.XOR<Prisma.UrlScalarRelationFilter, Prisma.UrlWhereInput>
}, "id" | "userId_urlId">

export type UserUrlOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.UserUrlCountOrderByAggregateInput
  _max?: Prisma.UserUrlMaxOrderByAggregateInput
  _min?: Prisma.UserUrlMinOrderByAggregateInput
}

export type UserUrlScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserUrlScalarWhereWithAggregatesInput | Prisma.UserUrlScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserUrlScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserUrlScalarWhereWithAggregatesInput | Prisma.UserUrlScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserUrl"> | string
  userId?: Prisma.StringWithAggregatesFilter<"UserUrl"> | string
  urlId?: Prisma.StringWithAggregatesFilter<"UserUrl"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserUrl"> | Date | string
}

export type UserUrlCreateInput = {
  id?: string
  userId: string
  createdAt?: Date | string
  url: Prisma.UrlCreateNestedOneWithoutUserUrlsInput
}

export type UserUrlUncheckedCreateInput = {
  id?: string
  userId: string
  urlId: string
  createdAt?: Date | string
}

export type UserUrlUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  url?: Prisma.UrlUpdateOneRequiredWithoutUserUrlsNestedInput
}

export type UserUrlUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  urlId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserUrlCreateManyInput = {
  id?: string
  userId: string
  urlId: string
  createdAt?: Date | string
}

export type UserUrlUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserUrlUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  urlId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserUrlListRelationFilter = {
  every?: Prisma.UserUrlWhereInput
  some?: Prisma.UserUrlWhereInput
  none?: Prisma.UserUrlWhereInput
}

export type UserUrlOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserUrlUserIdUrlIdCompoundUniqueInput = {
  userId: string
  urlId: string
}

export type UserUrlCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserUrlMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserUrlMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  urlId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserUrlCreateNestedManyWithoutUrlInput = {
  create?: Prisma.XOR<Prisma.UserUrlCreateWithoutUrlInput, Prisma.UserUrlUncheckedCreateWithoutUrlInput> | Prisma.UserUrlCreateWithoutUrlInput[] | Prisma.UserUrlUncheckedCreateWithoutUrlInput[]
  connectOrCreate?: Prisma.UserUrlCreateOrConnectWithoutUrlInput | Prisma.UserUrlCreateOrConnectWithoutUrlInput[]
  createMany?: Prisma.UserUrlCreateManyUrlInputEnvelope
  connect?: Prisma.UserUrlWhereUniqueInput | Prisma.UserUrlWhereUniqueInput[]
}

export type UserUrlUncheckedCreateNestedManyWithoutUrlInput = {
  create?: Prisma.XOR<Prisma.UserUrlCreateWithoutUrlInput, Prisma.UserUrlUncheckedCreateWithoutUrlInput> | Prisma.UserUrlCreateWithoutUrlInput[] | Prisma.UserUrlUncheckedCreateWithoutUrlInput[]
  connectOrCreate?: Prisma.UserUrlCreateOrConnectWithoutUrlInput | Prisma.UserUrlCreateOrConnectWithoutUrlInput[]
  createMany?: Prisma.UserUrlCreateManyUrlInputEnvelope
  connect?: Prisma.UserUrlWhereUniqueInput | Prisma.UserUrlWhereUniqueInput[]
}

export type UserUrlUpdateManyWithoutUrlNestedInput = {
  create?: Prisma.XOR<Prisma.UserUrlCreateWithoutUrlInput, Prisma.UserUrlUncheckedCreateWithoutUrlInput> | Prisma.UserUrlCreateWithoutUrlInput[] | Prisma.UserUrlUncheckedCreateWithoutUrlInput[]
  connectOrCreate?: Prisma.UserUrlCreateOrConnectWithoutUrlInput | Prisma.UserUrlCreateOrConnectWithoutUrlInput[]
  upsert?: Prisma.UserUrlUpsertWithWhereUniqueWithoutUrlInput | Prisma.UserUrlUpsertWithWhereUniqueWithoutUrlInput[]
  createMany?: Prisma.UserUrlCreateManyUrlInputEnvelope
  set?: Prisma.UserUrlWhereUniqueInput | Prisma.UserUrlWhereUniqueInput[]
  disconnect?: Prisma.UserUrlWhereUniqueInput | Prisma.UserUrlWhereUniqueInput[]
  delete?: Prisma.UserUrlWhereUniqueInput | Prisma.UserUrlWhereUniqueInput[]
  connect?: Prisma.UserUrlWhereUniqueInput | Prisma.UserUrlWhereUniqueInput[]
  update?: Prisma.UserUrlUpdateWithWhereUniqueWithoutUrlInput | Prisma.UserUrlUpdateWithWhereUniqueWithoutUrlInput[]
  updateMany?: Prisma.UserUrlUpdateManyWithWhereWithoutUrlInput | Prisma.UserUrlUpdateManyWithWhereWithoutUrlInput[]
  deleteMany?: Prisma.UserUrlScalarWhereInput | Prisma.UserUrlScalarWhereInput[]
}

export type UserUrlUncheckedUpdateManyWithoutUrlNestedInput = {
  create?: Prisma.XOR<Prisma.UserUrlCreateWithoutUrlInput, Prisma.UserUrlUncheckedCreateWithoutUrlInput> | Prisma.UserUrlCreateWithoutUrlInput[] | Prisma.UserUrlUncheckedCreateWithoutUrlInput[]
  connectOrCreate?: Prisma.UserUrlCreateOrConnectWithoutUrlInput | Prisma.UserUrlCreateOrConnectWithoutUrlInput[]
  upsert?: Prisma.UserUrlUpsertWithWhereUniqueWithoutUrlInput | Prisma.UserUrlUpsertWithWhereUniqueWithoutUrlInput[]
  createMany?: Prisma.UserUrlCreateManyUrlInputEnvelope
  set?: Prisma.UserUrlWhereUniqueInput | Prisma.UserUrlWhereUniqueInput[]
  disconnect?: Prisma.UserUrlWhereUniqueInput | Prisma.UserUrlWhereUniqueInput[]
  delete?: Prisma.UserUrlWhereUniqueInput | Prisma.UserUrlWhereUniqueInput[]
  connect?: Prisma.UserUrlWhereUniqueInput | Prisma.UserUrlWhereUniqueInput[]
  update?: Prisma.UserUrlUpdateWithWhereUniqueWithoutUrlInput | Prisma.UserUrlUpdateWithWhereUniqueWithoutUrlInput[]
  updateMany?: Prisma.UserUrlUpdateManyWithWhereWithoutUrlInput | Prisma.UserUrlUpdateManyWithWhereWithoutUrlInput[]
  deleteMany?: Prisma.UserUrlScalarWhereInput | Prisma.UserUrlScalarWhereInput[]
}

export type UserUrlCreateWithoutUrlInput = {
  id?: string
  userId: string
  createdAt?: Date | string
}

export type UserUrlUncheckedCreateWithoutUrlInput = {
  id?: string
  userId: string
  createdAt?: Date | string
}

export type UserUrlCreateOrConnectWithoutUrlInput = {
  where: Prisma.UserUrlWhereUniqueInput
  create: Prisma.XOR<Prisma.UserUrlCreateWithoutUrlInput, Prisma.UserUrlUncheckedCreateWithoutUrlInput>
}

export type UserUrlCreateManyUrlInputEnvelope = {
  data: Prisma.UserUrlCreateManyUrlInput | Prisma.UserUrlCreateManyUrlInput[]
  skipDuplicates?: boolean
}

export type UserUrlUpsertWithWhereUniqueWithoutUrlInput = {
  where: Prisma.UserUrlWhereUniqueInput
  update: Prisma.XOR<Prisma.UserUrlUpdateWithoutUrlInput, Prisma.UserUrlUncheckedUpdateWithoutUrlInput>
  create: Prisma.XOR<Prisma.UserUrlCreateWithoutUrlInput, Prisma.UserUrlUncheckedCreateWithoutUrlInput>
}

export type UserUrlUpdateWithWhereUniqueWithoutUrlInput = {
  where: Prisma.UserUrlWhereUniqueInput
  data: Prisma.XOR<Prisma.UserUrlUpdateWithoutUrlInput, Prisma.UserUrlUncheckedUpdateWithoutUrlInput>
}

export type UserUrlUpdateManyWithWhereWithoutUrlInput = {
  where: Prisma.UserUrlScalarWhereInput
  data: Prisma.XOR<Prisma.UserUrlUpdateManyMutationInput, Prisma.UserUrlUncheckedUpdateManyWithoutUrlInput>
}

export type UserUrlScalarWhereInput = {
  AND?: Prisma.UserUrlScalarWhereInput | Prisma.UserUrlScalarWhereInput[]
  OR?: Prisma.UserUrlScalarWhereInput[]
  NOT?: Prisma.UserUrlScalarWhereInput | Prisma.UserUrlScalarWhereInput[]
  id?: Prisma.StringFilter<"UserUrl"> | string
  userId?: Prisma.StringFilter<"UserUrl"> | string
  urlId?: Prisma.StringFilter<"UserUrl"> | string
  createdAt?: Prisma.DateTimeFilter<"UserUrl"> | Date | string
}

export type UserUrlCreateManyUrlInput = {
  id?: string
  userId: string
  createdAt?: Date | string
}

export type UserUrlUpdateWithoutUrlInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserUrlUncheckedUpdateWithoutUrlInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserUrlUncheckedUpdateManyWithoutUrlInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserUrlSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  urlId?: boolean
  createdAt?: boolean
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userUrl"]>

export type UserUrlSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  urlId?: boolean
  createdAt?: boolean
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userUrl"]>

export type UserUrlSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  urlId?: boolean
  createdAt?: boolean
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userUrl"]>

export type UserUrlSelectScalar = {
  id?: boolean
  userId?: boolean
  urlId?: boolean
  createdAt?: boolean
}

export type UserUrlOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "urlId" | "createdAt", ExtArgs["result"]["userUrl"]>
export type UserUrlInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}
export type UserUrlIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}
export type UserUrlIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  url?: boolean | Prisma.UrlDefaultArgs<ExtArgs>
}

export type $UserUrlPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserUrl"
  objects: {
    url: Prisma.$UrlPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    urlId: string
    createdAt: Date
  }, ExtArgs["result"]["userUrl"]>
  composites: {}
}

export type UserUrlGetPayload<S extends boolean | null | undefined | UserUrlDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserUrlPayload, S>

export type UserUrlCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserUrlFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserUrlCountAggregateInputType | true
  }

export interface UserUrlDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserUrl'], meta: { name: 'UserUrl' } }
  /**
   * Find zero or one UserUrl that matches the filter.
   * @param {UserUrlFindUniqueArgs} args - Arguments to find a UserUrl
   * @example
   * // Get one UserUrl
   * const userUrl = await prisma.userUrl.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserUrlFindUniqueArgs>(args: Prisma.SelectSubset<T, UserUrlFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserUrlClient<runtime.Types.Result.GetResult<Prisma.$UserUrlPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserUrl that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserUrlFindUniqueOrThrowArgs} args - Arguments to find a UserUrl
   * @example
   * // Get one UserUrl
   * const userUrl = await prisma.userUrl.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserUrlFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserUrlFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserUrlClient<runtime.Types.Result.GetResult<Prisma.$UserUrlPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserUrl that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUrlFindFirstArgs} args - Arguments to find a UserUrl
   * @example
   * // Get one UserUrl
   * const userUrl = await prisma.userUrl.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserUrlFindFirstArgs>(args?: Prisma.SelectSubset<T, UserUrlFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserUrlClient<runtime.Types.Result.GetResult<Prisma.$UserUrlPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserUrl that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUrlFindFirstOrThrowArgs} args - Arguments to find a UserUrl
   * @example
   * // Get one UserUrl
   * const userUrl = await prisma.userUrl.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserUrlFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserUrlFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserUrlClient<runtime.Types.Result.GetResult<Prisma.$UserUrlPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserUrls that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUrlFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserUrls
   * const userUrls = await prisma.userUrl.findMany()
   * 
   * // Get first 10 UserUrls
   * const userUrls = await prisma.userUrl.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userUrlWithIdOnly = await prisma.userUrl.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserUrlFindManyArgs>(args?: Prisma.SelectSubset<T, UserUrlFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserUrlPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserUrl.
   * @param {UserUrlCreateArgs} args - Arguments to create a UserUrl.
   * @example
   * // Create one UserUrl
   * const UserUrl = await prisma.userUrl.create({
   *   data: {
   *     // ... data to create a UserUrl
   *   }
   * })
   * 
   */
  create<T extends UserUrlCreateArgs>(args: Prisma.SelectSubset<T, UserUrlCreateArgs<ExtArgs>>): Prisma.Prisma__UserUrlClient<runtime.Types.Result.GetResult<Prisma.$UserUrlPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserUrls.
   * @param {UserUrlCreateManyArgs} args - Arguments to create many UserUrls.
   * @example
   * // Create many UserUrls
   * const userUrl = await prisma.userUrl.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserUrlCreateManyArgs>(args?: Prisma.SelectSubset<T, UserUrlCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserUrls and returns the data saved in the database.
   * @param {UserUrlCreateManyAndReturnArgs} args - Arguments to create many UserUrls.
   * @example
   * // Create many UserUrls
   * const userUrl = await prisma.userUrl.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserUrls and only return the `id`
   * const userUrlWithIdOnly = await prisma.userUrl.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserUrlCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserUrlCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserUrlPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserUrl.
   * @param {UserUrlDeleteArgs} args - Arguments to delete one UserUrl.
   * @example
   * // Delete one UserUrl
   * const UserUrl = await prisma.userUrl.delete({
   *   where: {
   *     // ... filter to delete one UserUrl
   *   }
   * })
   * 
   */
  delete<T extends UserUrlDeleteArgs>(args: Prisma.SelectSubset<T, UserUrlDeleteArgs<ExtArgs>>): Prisma.Prisma__UserUrlClient<runtime.Types.Result.GetResult<Prisma.$UserUrlPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserUrl.
   * @param {UserUrlUpdateArgs} args - Arguments to update one UserUrl.
   * @example
   * // Update one UserUrl
   * const userUrl = await prisma.userUrl.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUrlUpdateArgs>(args: Prisma.SelectSubset<T, UserUrlUpdateArgs<ExtArgs>>): Prisma.Prisma__UserUrlClient<runtime.Types.Result.GetResult<Prisma.$UserUrlPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserUrls.
   * @param {UserUrlDeleteManyArgs} args - Arguments to filter UserUrls to delete.
   * @example
   * // Delete a few UserUrls
   * const { count } = await prisma.userUrl.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserUrlDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserUrlDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserUrls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUrlUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserUrls
   * const userUrl = await prisma.userUrl.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUrlUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUrlUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserUrls and returns the data updated in the database.
   * @param {UserUrlUpdateManyAndReturnArgs} args - Arguments to update many UserUrls.
   * @example
   * // Update many UserUrls
   * const userUrl = await prisma.userUrl.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserUrls and only return the `id`
   * const userUrlWithIdOnly = await prisma.userUrl.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUrlUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUrlUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserUrlPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserUrl.
   * @param {UserUrlUpsertArgs} args - Arguments to update or create a UserUrl.
   * @example
   * // Update or create a UserUrl
   * const userUrl = await prisma.userUrl.upsert({
   *   create: {
   *     // ... data to create a UserUrl
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserUrl we want to update
   *   }
   * })
   */
  upsert<T extends UserUrlUpsertArgs>(args: Prisma.SelectSubset<T, UserUrlUpsertArgs<ExtArgs>>): Prisma.Prisma__UserUrlClient<runtime.Types.Result.GetResult<Prisma.$UserUrlPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserUrls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUrlCountArgs} args - Arguments to filter UserUrls to count.
   * @example
   * // Count the number of UserUrls
   * const count = await prisma.userUrl.count({
   *   where: {
   *     // ... the filter for the UserUrls we want to count
   *   }
   * })
  **/
  count<T extends UserUrlCountArgs>(
    args?: Prisma.Subset<T, UserUrlCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserUrlCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserUrl.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUrlAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserUrlAggregateArgs>(args: Prisma.Subset<T, UserUrlAggregateArgs>): Prisma.PrismaPromise<GetUserUrlAggregateType<T>>

  /**
   * Group by UserUrl.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUrlGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserUrlGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserUrlGroupByArgs['orderBy'] }
      : { orderBy?: UserUrlGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserUrlGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserUrlGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserUrl model
 */
readonly fields: UserUrlFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserUrl.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserUrlClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  url<T extends Prisma.UrlDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UrlDefaultArgs<ExtArgs>>): Prisma.Prisma__UrlClient<runtime.Types.Result.GetResult<Prisma.$UrlPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserUrl model
 */
export interface UserUrlFieldRefs {
  readonly id: Prisma.FieldRef<"UserUrl", 'String'>
  readonly userId: Prisma.FieldRef<"UserUrl", 'String'>
  readonly urlId: Prisma.FieldRef<"UserUrl", 'String'>
  readonly createdAt: Prisma.FieldRef<"UserUrl", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserUrl findUnique
 */
export type UserUrlFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserUrl
   */
  select?: Prisma.UserUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserUrl
   */
  omit?: Prisma.UserUrlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserUrlInclude<ExtArgs> | null
  /**
   * Filter, which UserUrl to fetch.
   */
  where: Prisma.UserUrlWhereUniqueInput
}

/**
 * UserUrl findUniqueOrThrow
 */
export type UserUrlFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserUrl
   */
  select?: Prisma.UserUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserUrl
   */
  omit?: Prisma.UserUrlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserUrlInclude<ExtArgs> | null
  /**
   * Filter, which UserUrl to fetch.
   */
  where: Prisma.UserUrlWhereUniqueInput
}

/**
 * UserUrl findFirst
 */
export type UserUrlFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserUrl
   */
  select?: Prisma.UserUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserUrl
   */
  omit?: Prisma.UserUrlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserUrlInclude<ExtArgs> | null
  /**
   * Filter, which UserUrl to fetch.
   */
  where?: Prisma.UserUrlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserUrls to fetch.
   */
  orderBy?: Prisma.UserUrlOrderByWithRelationInput | Prisma.UserUrlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserUrls.
   */
  cursor?: Prisma.UserUrlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserUrls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserUrls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserUrls.
   */
  distinct?: Prisma.UserUrlScalarFieldEnum | Prisma.UserUrlScalarFieldEnum[]
}

/**
 * UserUrl findFirstOrThrow
 */
export type UserUrlFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserUrl
   */
  select?: Prisma.UserUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserUrl
   */
  omit?: Prisma.UserUrlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserUrlInclude<ExtArgs> | null
  /**
   * Filter, which UserUrl to fetch.
   */
  where?: Prisma.UserUrlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserUrls to fetch.
   */
  orderBy?: Prisma.UserUrlOrderByWithRelationInput | Prisma.UserUrlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserUrls.
   */
  cursor?: Prisma.UserUrlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserUrls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserUrls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserUrls.
   */
  distinct?: Prisma.UserUrlScalarFieldEnum | Prisma.UserUrlScalarFieldEnum[]
}

/**
 * UserUrl findMany
 */
export type UserUrlFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserUrl
   */
  select?: Prisma.UserUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserUrl
   */
  omit?: Prisma.UserUrlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserUrlInclude<ExtArgs> | null
  /**
   * Filter, which UserUrls to fetch.
   */
  where?: Prisma.UserUrlWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserUrls to fetch.
   */
  orderBy?: Prisma.UserUrlOrderByWithRelationInput | Prisma.UserUrlOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserUrls.
   */
  cursor?: Prisma.UserUrlWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserUrls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserUrls.
   */
  skip?: number
  distinct?: Prisma.UserUrlScalarFieldEnum | Prisma.UserUrlScalarFieldEnum[]
}

/**
 * UserUrl create
 */
export type UserUrlCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserUrl
   */
  select?: Prisma.UserUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserUrl
   */
  omit?: Prisma.UserUrlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserUrlInclude<ExtArgs> | null
  /**
   * The data needed to create a UserUrl.
   */
  data: Prisma.XOR<Prisma.UserUrlCreateInput, Prisma.UserUrlUncheckedCreateInput>
}

/**
 * UserUrl createMany
 */
export type UserUrlCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserUrls.
   */
  data: Prisma.UserUrlCreateManyInput | Prisma.UserUrlCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserUrl createManyAndReturn
 */
export type UserUrlCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserUrl
   */
  select?: Prisma.UserUrlSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserUrl
   */
  omit?: Prisma.UserUrlOmit<ExtArgs> | null
  /**
   * The data used to create many UserUrls.
   */
  data: Prisma.UserUrlCreateManyInput | Prisma.UserUrlCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserUrlIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserUrl update
 */
export type UserUrlUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserUrl
   */
  select?: Prisma.UserUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserUrl
   */
  omit?: Prisma.UserUrlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserUrlInclude<ExtArgs> | null
  /**
   * The data needed to update a UserUrl.
   */
  data: Prisma.XOR<Prisma.UserUrlUpdateInput, Prisma.UserUrlUncheckedUpdateInput>
  /**
   * Choose, which UserUrl to update.
   */
  where: Prisma.UserUrlWhereUniqueInput
}

/**
 * UserUrl updateMany
 */
export type UserUrlUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserUrls.
   */
  data: Prisma.XOR<Prisma.UserUrlUpdateManyMutationInput, Prisma.UserUrlUncheckedUpdateManyInput>
  /**
   * Filter which UserUrls to update
   */
  where?: Prisma.UserUrlWhereInput
  /**
   * Limit how many UserUrls to update.
   */
  limit?: number
}

/**
 * UserUrl updateManyAndReturn
 */
export type UserUrlUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserUrl
   */
  select?: Prisma.UserUrlSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserUrl
   */
  omit?: Prisma.UserUrlOmit<ExtArgs> | null
  /**
   * The data used to update UserUrls.
   */
  data: Prisma.XOR<Prisma.UserUrlUpdateManyMutationInput, Prisma.UserUrlUncheckedUpdateManyInput>
  /**
   * Filter which UserUrls to update
   */
  where?: Prisma.UserUrlWhereInput
  /**
   * Limit how many UserUrls to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserUrlIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserUrl upsert
 */
export type UserUrlUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserUrl
   */
  select?: Prisma.UserUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserUrl
   */
  omit?: Prisma.UserUrlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserUrlInclude<ExtArgs> | null
  /**
   * The filter to search for the UserUrl to update in case it exists.
   */
  where: Prisma.UserUrlWhereUniqueInput
  /**
   * In case the UserUrl found by the `where` argument doesn't exist, create a new UserUrl with this data.
   */
  create: Prisma.XOR<Prisma.UserUrlCreateInput, Prisma.UserUrlUncheckedCreateInput>
  /**
   * In case the UserUrl was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUrlUpdateInput, Prisma.UserUrlUncheckedUpdateInput>
}

/**
 * UserUrl delete
 */
export type UserUrlDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserUrl
   */
  select?: Prisma.UserUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserUrl
   */
  omit?: Prisma.UserUrlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserUrlInclude<ExtArgs> | null
  /**
   * Filter which UserUrl to delete.
   */
  where: Prisma.UserUrlWhereUniqueInput
}

/**
 * UserUrl deleteMany
 */
export type UserUrlDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserUrls to delete
   */
  where?: Prisma.UserUrlWhereInput
  /**
   * Limit how many UserUrls to delete.
   */
  limit?: number
}

/**
 * UserUrl without action
 */
export type UserUrlDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserUrl
   */
  select?: Prisma.UserUrlSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserUrl
   */
  omit?: Prisma.UserUrlOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserUrlInclude<ExtArgs> | null
}
