
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Url
 * 
 */
export type Url = Prisma.UrlModel
/**
 * Model LinkMetadata
 * 
 */
export type LinkMetadata = Prisma.LinkMetadataModel
/**
 * Model RotationLink
 * 
 */
export type RotationLink = Prisma.RotationLinkModel
/**
 * Model HealthCheck
 * 
 */
export type HealthCheck = Prisma.HealthCheckModel
/**
 * Model UserUrl
 * 
 */
export type UserUrl = Prisma.UserUrlModel
/**
 * Model Analytics
 * 
 */
export type Analytics = Prisma.AnalyticsModel
/**
 * Model ClickEvent
 * 
 */
export type ClickEvent = Prisma.ClickEventModel
/**
 * Model Report
 * 
 */
export type Report = Prisma.ReportModel
/**
 * Model UrlScan
 * 
 */
export type UrlScan = Prisma.UrlScanModel
/**
 * Model RateLimit
 * 
 */
export type RateLimit = Prisma.RateLimitModel
/**
 * Model BannedIp
 * 
 */
export type BannedIp = Prisma.BannedIpModel
/**
 * Model BannedDomain
 * 
 */
export type BannedDomain = Prisma.BannedDomainModel
/**
 * Model AdminConfig
 * 
 */
export type AdminConfig = Prisma.AdminConfigModel
/**
 * Model ApiKey
 * 
 */
export type ApiKey = Prisma.ApiKeyModel
/**
 * Model ApiKeyUsage
 * 
 */
export type ApiKeyUsage = Prisma.ApiKeyUsageModel
