
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Urls
 * const urls = await prisma.url.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Url
 * 
 */
export type Url = Prisma.UrlModel
/**
 * Model LinkMetadata
 * 
 */
export type LinkMetadata = Prisma.LinkMetadataModel
/**
 * Model RotationLink
 * 
 */
export type RotationLink = Prisma.RotationLinkModel
/**
 * Model HealthCheck
 * 
 */
export type HealthCheck = Prisma.HealthCheckModel
/**
 * Model UserUrl
 * 
 */
export type UserUrl = Prisma.UserUrlModel
/**
 * Model Analytics
 * 
 */
export type Analytics = Prisma.AnalyticsModel
/**
 * Model ClickEvent
 * 
 */
export type ClickEvent = Prisma.ClickEventModel
/**
 * Model Report
 * 
 */
export type Report = Prisma.ReportModel
/**
 * Model UrlScan
 * 
 */
export type UrlScan = Prisma.UrlScanModel
/**
 * Model RateLimit
 * 
 */
export type RateLimit = Prisma.RateLimitModel
/**
 * Model BannedIp
 * 
 */
export type BannedIp = Prisma.BannedIpModel
/**
 * Model BannedDomain
 * 
 */
export type BannedDomain = Prisma.BannedDomainModel
/**
 * Model AdminConfig
 * 
 */
export type AdminConfig = Prisma.AdminConfigModel
/**
 * Model ApiKey
 * 
 */
export type ApiKey = Prisma.ApiKeyModel
/**
 * Model ApiKeyUsage
 * 
 */
export type ApiKeyUsage = Prisma.ApiKeyUsageModel
