
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const HealthStatus = {
  HEALTHY: 'HEALTHY',
  WARNING: 'WARNING',
  BROKEN: 'BROKEN',
  UNKNOWN: 'UNKNOWN'
} as const

export type HealthStatus = (typeof HealthStatus)[keyof typeof HealthStatus]


export const ReportStatus = {
  PENDING: 'PENDING',
  REVIEWED: 'REVIEWED',
  DISMISSED: 'DISMISSED'
} as const

export type ReportStatus = (typeof ReportStatus)[keyof typeof ReportStatus]
