
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Url: 'Url',
  LinkMetadata: 'LinkMetadata',
  RotationLink: 'RotationLink',
  HealthCheck: 'HealthCheck',
  UserUrl: 'UserUrl',
  Analytics: 'Analytics',
  ClickEvent: 'ClickEvent',
  Report: 'Report',
  UrlScan: 'UrlScan',
  RateLimit: 'RateLimit',
  BannedIp: 'BannedIp',
  BannedDomain: 'BannedDomain',
  AdminConfig: 'AdminConfig',
  ApiKey: 'ApiKey',
  ApiKeyUsage: 'ApiKeyUsage'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UrlScalarFieldEnum = {
  id: 'id',
  originalUrl: 'originalUrl',
  urlHash: 'urlHash',
  shortCode: 'shortCode',
  createdAt: 'createdAt',
  expiresAt: 'expiresAt',
  isActive: 'isActive',
  isFlagged: 'isFlagged',
  flagReason: 'flagReason',
  isPasswordProtected: 'isPasswordProtected',
  passwordHash: 'passwordHash',
  isRotation: 'isRotation',
  rotationType: 'rotationType',
  currentRotation: 'currentRotation',
  lastHealthCheck: 'lastHealthCheck',
  healthStatus: 'healthStatus',
  lastStatusCode: 'lastStatusCode',
  healthCheckError: 'healthCheckError'
} as const

export type UrlScalarFieldEnum = (typeof UrlScalarFieldEnum)[keyof typeof UrlScalarFieldEnum]


export const LinkMetadataScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  title: 'title',
  description: 'description',
  image: 'image',
  logo: 'logo',
  author: 'author',
  publisher: 'publisher',
  date: 'date',
  favicon: 'favicon',
  scrapedAt: 'scrapedAt'
} as const

export type LinkMetadataScalarFieldEnum = (typeof LinkMetadataScalarFieldEnum)[keyof typeof LinkMetadataScalarFieldEnum]


export const RotationLinkScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  destination: 'destination',
  weight: 'weight',
  label: 'label',
  clicks: 'clicks',
  isActive: 'isActive',
  createdAt: 'createdAt'
} as const

export type RotationLinkScalarFieldEnum = (typeof RotationLinkScalarFieldEnum)[keyof typeof RotationLinkScalarFieldEnum]


export const HealthCheckScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  checkedAt: 'checkedAt',
  statusCode: 'statusCode',
  responseTime: 'responseTime',
  status: 'status',
  errorMessage: 'errorMessage'
} as const

export type HealthCheckScalarFieldEnum = (typeof HealthCheckScalarFieldEnum)[keyof typeof HealthCheckScalarFieldEnum]


export const UserUrlScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  urlId: 'urlId',
  createdAt: 'createdAt'
} as const

export type UserUrlScalarFieldEnum = (typeof UserUrlScalarFieldEnum)[keyof typeof UserUrlScalarFieldEnum]


export const AnalyticsScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  clicks: 'clicks',
  lastClick: 'lastClick',
  ipHash: 'ipHash',
  userAgent: 'userAgent',
  referer: 'referer',
  country: 'country'
} as const

export type AnalyticsScalarFieldEnum = (typeof AnalyticsScalarFieldEnum)[keyof typeof AnalyticsScalarFieldEnum]


export const ClickEventScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  clickedAt: 'clickedAt',
  ipHash: 'ipHash',
  userAgent: 'userAgent',
  referer: 'referer',
  country: 'country',
  city: 'city',
  device: 'device',
  browser: 'browser',
  os: 'os',
  utmSource: 'utmSource',
  utmMedium: 'utmMedium',
  utmCampaign: 'utmCampaign'
} as const

export type ClickEventScalarFieldEnum = (typeof ClickEventScalarFieldEnum)[keyof typeof ClickEventScalarFieldEnum]


export const ReportScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  reportedBy: 'reportedBy',
  reason: 'reason',
  createdAt: 'createdAt',
  status: 'status',
  reviewedBy: 'reviewedBy',
  reviewedAt: 'reviewedAt'
} as const

export type ReportScalarFieldEnum = (typeof ReportScalarFieldEnum)[keyof typeof ReportScalarFieldEnum]


export const UrlScanScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  service: 'service',
  result: 'result',
  details: 'details',
  scannedAt: 'scannedAt'
} as const

export type UrlScanScalarFieldEnum = (typeof UrlScanScalarFieldEnum)[keyof typeof UrlScanScalarFieldEnum]


export const RateLimitScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  tokens: 'tokens',
  lastRefill: 'lastRefill'
} as const

export type RateLimitScalarFieldEnum = (typeof RateLimitScalarFieldEnum)[keyof typeof RateLimitScalarFieldEnum]


export const BannedIpScalarFieldEnum = {
  id: 'id',
  ip: 'ip',
  reason: 'reason',
  bannedAt: 'bannedAt',
  bannedBy: 'bannedBy'
} as const

export type BannedIpScalarFieldEnum = (typeof BannedIpScalarFieldEnum)[keyof typeof BannedIpScalarFieldEnum]


export const BannedDomainScalarFieldEnum = {
  id: 'id',
  domain: 'domain',
  reason: 'reason',
  bannedAt: 'bannedAt',
  bannedBy: 'bannedBy'
} as const

export type BannedDomainScalarFieldEnum = (typeof BannedDomainScalarFieldEnum)[keyof typeof BannedDomainScalarFieldEnum]


export const AdminConfigScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value'
} as const

export type AdminConfigScalarFieldEnum = (typeof AdminConfigScalarFieldEnum)[keyof typeof AdminConfigScalarFieldEnum]


export const ApiKeyScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  key: 'key',
  keyPrefix: 'keyPrefix',
  isActive: 'isActive',
  createdAt: 'createdAt',
  lastUsed: 'lastUsed',
  expiresAt: 'expiresAt',
  requestCount: 'requestCount',
  rateLimit: 'rateLimit',
  bypassSecurity: 'bypassSecurity',
  bypassRateLimit: 'bypassRateLimit'
} as const

export type ApiKeyScalarFieldEnum = (typeof ApiKeyScalarFieldEnum)[keyof typeof ApiKeyScalarFieldEnum]


export const ApiKeyUsageScalarFieldEnum = {
  id: 'id',
  apiKeyId: 'apiKeyId',
  endpoint: 'endpoint',
  method: 'method',
  status: 'status',
  timestamp: 'timestamp',
  ipAddress: 'ipAddress'
} as const

export type ApiKeyUsageScalarFieldEnum = (typeof ApiKeyUsageScalarFieldEnum)[keyof typeof ApiKeyUsageScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull'
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

