
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
export const prismaVersion: PrismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Url: 'Url',
  LinkMetadata: 'LinkMetadata',
  RotationLink: 'RotationLink',
  HealthCheck: 'HealthCheck',
  UserUrl: 'UserUrl',
  Analytics: 'Analytics',
  ClickEvent: 'ClickEvent',
  Report: 'Report',
  UrlScan: 'UrlScan',
  RateLimit: 'RateLimit',
  BannedIp: 'BannedIp',
  BannedDomain: 'BannedDomain',
  AdminConfig: 'AdminConfig',
  ApiKey: 'ApiKey',
  ApiKeyUsage: 'ApiKeyUsage'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "url" | "linkMetadata" | "rotationLink" | "healthCheck" | "userUrl" | "analytics" | "clickEvent" | "report" | "urlScan" | "rateLimit" | "bannedIp" | "bannedDomain" | "adminConfig" | "apiKey" | "apiKeyUsage"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Url: {
      payload: Prisma.$UrlPayload<ExtArgs>
      fields: Prisma.UrlFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UrlFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UrlFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>
        }
        findFirst: {
          args: Prisma.UrlFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UrlFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>
        }
        findMany: {
          args: Prisma.UrlFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>[]
        }
        create: {
          args: Prisma.UrlCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>
        }
        createMany: {
          args: Prisma.UrlCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UrlCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>[]
        }
        delete: {
          args: Prisma.UrlDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>
        }
        update: {
          args: Prisma.UrlUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>
        }
        deleteMany: {
          args: Prisma.UrlDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UrlUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UrlUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>[]
        }
        upsert: {
          args: Prisma.UrlUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlPayload>
        }
        aggregate: {
          args: Prisma.UrlAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUrl>
        }
        groupBy: {
          args: Prisma.UrlGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UrlGroupByOutputType>[]
        }
        count: {
          args: Prisma.UrlCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UrlCountAggregateOutputType> | number
        }
      }
    }
    LinkMetadata: {
      payload: Prisma.$LinkMetadataPayload<ExtArgs>
      fields: Prisma.LinkMetadataFieldRefs
      operations: {
        findUnique: {
          args: Prisma.LinkMetadataFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkMetadataPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.LinkMetadataFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkMetadataPayload>
        }
        findFirst: {
          args: Prisma.LinkMetadataFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkMetadataPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.LinkMetadataFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkMetadataPayload>
        }
        findMany: {
          args: Prisma.LinkMetadataFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkMetadataPayload>[]
        }
        create: {
          args: Prisma.LinkMetadataCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkMetadataPayload>
        }
        createMany: {
          args: Prisma.LinkMetadataCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.LinkMetadataCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkMetadataPayload>[]
        }
        delete: {
          args: Prisma.LinkMetadataDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkMetadataPayload>
        }
        update: {
          args: Prisma.LinkMetadataUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkMetadataPayload>
        }
        deleteMany: {
          args: Prisma.LinkMetadataDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.LinkMetadataUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.LinkMetadataUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkMetadataPayload>[]
        }
        upsert: {
          args: Prisma.LinkMetadataUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkMetadataPayload>
        }
        aggregate: {
          args: Prisma.LinkMetadataAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateLinkMetadata>
        }
        groupBy: {
          args: Prisma.LinkMetadataGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LinkMetadataGroupByOutputType>[]
        }
        count: {
          args: Prisma.LinkMetadataCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LinkMetadataCountAggregateOutputType> | number
        }
      }
    }
    RotationLink: {
      payload: Prisma.$RotationLinkPayload<ExtArgs>
      fields: Prisma.RotationLinkFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RotationLinkFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RotationLinkPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RotationLinkFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RotationLinkPayload>
        }
        findFirst: {
          args: Prisma.RotationLinkFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RotationLinkPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RotationLinkFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RotationLinkPayload>
        }
        findMany: {
          args: Prisma.RotationLinkFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RotationLinkPayload>[]
        }
        create: {
          args: Prisma.RotationLinkCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RotationLinkPayload>
        }
        createMany: {
          args: Prisma.RotationLinkCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RotationLinkCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RotationLinkPayload>[]
        }
        delete: {
          args: Prisma.RotationLinkDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RotationLinkPayload>
        }
        update: {
          args: Prisma.RotationLinkUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RotationLinkPayload>
        }
        deleteMany: {
          args: Prisma.RotationLinkDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RotationLinkUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RotationLinkUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RotationLinkPayload>[]
        }
        upsert: {
          args: Prisma.RotationLinkUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RotationLinkPayload>
        }
        aggregate: {
          args: Prisma.RotationLinkAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRotationLink>
        }
        groupBy: {
          args: Prisma.RotationLinkGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RotationLinkGroupByOutputType>[]
        }
        count: {
          args: Prisma.RotationLinkCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RotationLinkCountAggregateOutputType> | number
        }
      }
    }
    HealthCheck: {
      payload: Prisma.$HealthCheckPayload<ExtArgs>
      fields: Prisma.HealthCheckFieldRefs
      operations: {
        findUnique: {
          args: Prisma.HealthCheckFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HealthCheckPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.HealthCheckFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HealthCheckPayload>
        }
        findFirst: {
          args: Prisma.HealthCheckFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HealthCheckPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.HealthCheckFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HealthCheckPayload>
        }
        findMany: {
          args: Prisma.HealthCheckFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HealthCheckPayload>[]
        }
        create: {
          args: Prisma.HealthCheckCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HealthCheckPayload>
        }
        createMany: {
          args: Prisma.HealthCheckCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.HealthCheckCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HealthCheckPayload>[]
        }
        delete: {
          args: Prisma.HealthCheckDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HealthCheckPayload>
        }
        update: {
          args: Prisma.HealthCheckUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HealthCheckPayload>
        }
        deleteMany: {
          args: Prisma.HealthCheckDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.HealthCheckUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.HealthCheckUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HealthCheckPayload>[]
        }
        upsert: {
          args: Prisma.HealthCheckUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HealthCheckPayload>
        }
        aggregate: {
          args: Prisma.HealthCheckAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateHealthCheck>
        }
        groupBy: {
          args: Prisma.HealthCheckGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.HealthCheckGroupByOutputType>[]
        }
        count: {
          args: Prisma.HealthCheckCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.HealthCheckCountAggregateOutputType> | number
        }
      }
    }
    UserUrl: {
      payload: Prisma.$UserUrlPayload<ExtArgs>
      fields: Prisma.UserUrlFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserUrlFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserUrlPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserUrlFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserUrlPayload>
        }
        findFirst: {
          args: Prisma.UserUrlFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserUrlPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserUrlFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserUrlPayload>
        }
        findMany: {
          args: Prisma.UserUrlFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserUrlPayload>[]
        }
        create: {
          args: Prisma.UserUrlCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserUrlPayload>
        }
        createMany: {
          args: Prisma.UserUrlCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserUrlCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserUrlPayload>[]
        }
        delete: {
          args: Prisma.UserUrlDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserUrlPayload>
        }
        update: {
          args: Prisma.UserUrlUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserUrlPayload>
        }
        deleteMany: {
          args: Prisma.UserUrlDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUrlUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUrlUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserUrlPayload>[]
        }
        upsert: {
          args: Prisma.UserUrlUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserUrlPayload>
        }
        aggregate: {
          args: Prisma.UserUrlAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserUrl>
        }
        groupBy: {
          args: Prisma.UserUrlGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserUrlGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserUrlCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserUrlCountAggregateOutputType> | number
        }
      }
    }
    Analytics: {
      payload: Prisma.$AnalyticsPayload<ExtArgs>
      fields: Prisma.AnalyticsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AnalyticsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AnalyticsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AnalyticsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AnalyticsPayload>
        }
        findFirst: {
          args: Prisma.AnalyticsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AnalyticsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AnalyticsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AnalyticsPayload>
        }
        findMany: {
          args: Prisma.AnalyticsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AnalyticsPayload>[]
        }
        create: {
          args: Prisma.AnalyticsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AnalyticsPayload>
        }
        createMany: {
          args: Prisma.AnalyticsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AnalyticsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AnalyticsPayload>[]
        }
        delete: {
          args: Prisma.AnalyticsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AnalyticsPayload>
        }
        update: {
          args: Prisma.AnalyticsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AnalyticsPayload>
        }
        deleteMany: {
          args: Prisma.AnalyticsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AnalyticsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AnalyticsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AnalyticsPayload>[]
        }
        upsert: {
          args: Prisma.AnalyticsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AnalyticsPayload>
        }
        aggregate: {
          args: Prisma.AnalyticsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAnalytics>
        }
        groupBy: {
          args: Prisma.AnalyticsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AnalyticsGroupByOutputType>[]
        }
        count: {
          args: Prisma.AnalyticsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AnalyticsCountAggregateOutputType> | number
        }
      }
    }
    ClickEvent: {
      payload: Prisma.$ClickEventPayload<ExtArgs>
      fields: Prisma.ClickEventFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ClickEventFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClickEventPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ClickEventFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClickEventPayload>
        }
        findFirst: {
          args: Prisma.ClickEventFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClickEventPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ClickEventFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClickEventPayload>
        }
        findMany: {
          args: Prisma.ClickEventFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClickEventPayload>[]
        }
        create: {
          args: Prisma.ClickEventCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClickEventPayload>
        }
        createMany: {
          args: Prisma.ClickEventCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ClickEventCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClickEventPayload>[]
        }
        delete: {
          args: Prisma.ClickEventDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClickEventPayload>
        }
        update: {
          args: Prisma.ClickEventUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClickEventPayload>
        }
        deleteMany: {
          args: Prisma.ClickEventDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ClickEventUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ClickEventUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClickEventPayload>[]
        }
        upsert: {
          args: Prisma.ClickEventUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClickEventPayload>
        }
        aggregate: {
          args: Prisma.ClickEventAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateClickEvent>
        }
        groupBy: {
          args: Prisma.ClickEventGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ClickEventGroupByOutputType>[]
        }
        count: {
          args: Prisma.ClickEventCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ClickEventCountAggregateOutputType> | number
        }
      }
    }
    Report: {
      payload: Prisma.$ReportPayload<ExtArgs>
      fields: Prisma.ReportFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ReportFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReportPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ReportFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReportPayload>
        }
        findFirst: {
          args: Prisma.ReportFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReportPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ReportFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReportPayload>
        }
        findMany: {
          args: Prisma.ReportFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReportPayload>[]
        }
        create: {
          args: Prisma.ReportCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReportPayload>
        }
        createMany: {
          args: Prisma.ReportCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ReportCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReportPayload>[]
        }
        delete: {
          args: Prisma.ReportDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReportPayload>
        }
        update: {
          args: Prisma.ReportUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReportPayload>
        }
        deleteMany: {
          args: Prisma.ReportDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ReportUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ReportUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReportPayload>[]
        }
        upsert: {
          args: Prisma.ReportUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReportPayload>
        }
        aggregate: {
          args: Prisma.ReportAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateReport>
        }
        groupBy: {
          args: Prisma.ReportGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ReportGroupByOutputType>[]
        }
        count: {
          args: Prisma.ReportCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ReportCountAggregateOutputType> | number
        }
      }
    }
    UrlScan: {
      payload: Prisma.$UrlScanPayload<ExtArgs>
      fields: Prisma.UrlScanFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UrlScanFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlScanPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UrlScanFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlScanPayload>
        }
        findFirst: {
          args: Prisma.UrlScanFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlScanPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UrlScanFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlScanPayload>
        }
        findMany: {
          args: Prisma.UrlScanFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlScanPayload>[]
        }
        create: {
          args: Prisma.UrlScanCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlScanPayload>
        }
        createMany: {
          args: Prisma.UrlScanCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UrlScanCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlScanPayload>[]
        }
        delete: {
          args: Prisma.UrlScanDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlScanPayload>
        }
        update: {
          args: Prisma.UrlScanUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlScanPayload>
        }
        deleteMany: {
          args: Prisma.UrlScanDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UrlScanUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UrlScanUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlScanPayload>[]
        }
        upsert: {
          args: Prisma.UrlScanUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UrlScanPayload>
        }
        aggregate: {
          args: Prisma.UrlScanAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUrlScan>
        }
        groupBy: {
          args: Prisma.UrlScanGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UrlScanGroupByOutputType>[]
        }
        count: {
          args: Prisma.UrlScanCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UrlScanCountAggregateOutputType> | number
        }
      }
    }
    RateLimit: {
      payload: Prisma.$RateLimitPayload<ExtArgs>
      fields: Prisma.RateLimitFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RateLimitFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RateLimitPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RateLimitFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RateLimitPayload>
        }
        findFirst: {
          args: Prisma.RateLimitFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RateLimitPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RateLimitFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RateLimitPayload>
        }
        findMany: {
          args: Prisma.RateLimitFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RateLimitPayload>[]
        }
        create: {
          args: Prisma.RateLimitCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RateLimitPayload>
        }
        createMany: {
          args: Prisma.RateLimitCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RateLimitCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RateLimitPayload>[]
        }
        delete: {
          args: Prisma.RateLimitDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RateLimitPayload>
        }
        update: {
          args: Prisma.RateLimitUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RateLimitPayload>
        }
        deleteMany: {
          args: Prisma.RateLimitDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RateLimitUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RateLimitUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RateLimitPayload>[]
        }
        upsert: {
          args: Prisma.RateLimitUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RateLimitPayload>
        }
        aggregate: {
          args: Prisma.RateLimitAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRateLimit>
        }
        groupBy: {
          args: Prisma.RateLimitGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RateLimitGroupByOutputType>[]
        }
        count: {
          args: Prisma.RateLimitCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RateLimitCountAggregateOutputType> | number
        }
      }
    }
    BannedIp: {
      payload: Prisma.$BannedIpPayload<ExtArgs>
      fields: Prisma.BannedIpFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BannedIpFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedIpPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BannedIpFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedIpPayload>
        }
        findFirst: {
          args: Prisma.BannedIpFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedIpPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BannedIpFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedIpPayload>
        }
        findMany: {
          args: Prisma.BannedIpFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedIpPayload>[]
        }
        create: {
          args: Prisma.BannedIpCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedIpPayload>
        }
        createMany: {
          args: Prisma.BannedIpCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BannedIpCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedIpPayload>[]
        }
        delete: {
          args: Prisma.BannedIpDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedIpPayload>
        }
        update: {
          args: Prisma.BannedIpUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedIpPayload>
        }
        deleteMany: {
          args: Prisma.BannedIpDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BannedIpUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BannedIpUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedIpPayload>[]
        }
        upsert: {
          args: Prisma.BannedIpUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedIpPayload>
        }
        aggregate: {
          args: Prisma.BannedIpAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBannedIp>
        }
        groupBy: {
          args: Prisma.BannedIpGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BannedIpGroupByOutputType>[]
        }
        count: {
          args: Prisma.BannedIpCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BannedIpCountAggregateOutputType> | number
        }
      }
    }
    BannedDomain: {
      payload: Prisma.$BannedDomainPayload<ExtArgs>
      fields: Prisma.BannedDomainFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BannedDomainFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedDomainPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BannedDomainFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedDomainPayload>
        }
        findFirst: {
          args: Prisma.BannedDomainFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedDomainPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BannedDomainFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedDomainPayload>
        }
        findMany: {
          args: Prisma.BannedDomainFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedDomainPayload>[]
        }
        create: {
          args: Prisma.BannedDomainCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedDomainPayload>
        }
        createMany: {
          args: Prisma.BannedDomainCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BannedDomainCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedDomainPayload>[]
        }
        delete: {
          args: Prisma.BannedDomainDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedDomainPayload>
        }
        update: {
          args: Prisma.BannedDomainUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedDomainPayload>
        }
        deleteMany: {
          args: Prisma.BannedDomainDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BannedDomainUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BannedDomainUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedDomainPayload>[]
        }
        upsert: {
          args: Prisma.BannedDomainUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannedDomainPayload>
        }
        aggregate: {
          args: Prisma.BannedDomainAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBannedDomain>
        }
        groupBy: {
          args: Prisma.BannedDomainGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BannedDomainGroupByOutputType>[]
        }
        count: {
          args: Prisma.BannedDomainCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BannedDomainCountAggregateOutputType> | number
        }
      }
    }
    AdminConfig: {
      payload: Prisma.$AdminConfigPayload<ExtArgs>
      fields: Prisma.AdminConfigFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AdminConfigFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdminConfigPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AdminConfigFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdminConfigPayload>
        }
        findFirst: {
          args: Prisma.AdminConfigFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdminConfigPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AdminConfigFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdminConfigPayload>
        }
        findMany: {
          args: Prisma.AdminConfigFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdminConfigPayload>[]
        }
        create: {
          args: Prisma.AdminConfigCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdminConfigPayload>
        }
        createMany: {
          args: Prisma.AdminConfigCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AdminConfigCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdminConfigPayload>[]
        }
        delete: {
          args: Prisma.AdminConfigDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdminConfigPayload>
        }
        update: {
          args: Prisma.AdminConfigUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdminConfigPayload>
        }
        deleteMany: {
          args: Prisma.AdminConfigDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AdminConfigUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AdminConfigUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdminConfigPayload>[]
        }
        upsert: {
          args: Prisma.AdminConfigUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdminConfigPayload>
        }
        aggregate: {
          args: Prisma.AdminConfigAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAdminConfig>
        }
        groupBy: {
          args: Prisma.AdminConfigGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AdminConfigGroupByOutputType>[]
        }
        count: {
          args: Prisma.AdminConfigCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AdminConfigCountAggregateOutputType> | number
        }
      }
    }
    ApiKey: {
      payload: Prisma.$ApiKeyPayload<ExtArgs>
      fields: Prisma.ApiKeyFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ApiKeyFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ApiKeyFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyPayload>
        }
        findFirst: {
          args: Prisma.ApiKeyFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ApiKeyFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyPayload>
        }
        findMany: {
          args: Prisma.ApiKeyFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyPayload>[]
        }
        create: {
          args: Prisma.ApiKeyCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyPayload>
        }
        createMany: {
          args: Prisma.ApiKeyCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ApiKeyCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyPayload>[]
        }
        delete: {
          args: Prisma.ApiKeyDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyPayload>
        }
        update: {
          args: Prisma.ApiKeyUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyPayload>
        }
        deleteMany: {
          args: Prisma.ApiKeyDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ApiKeyUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ApiKeyUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyPayload>[]
        }
        upsert: {
          args: Prisma.ApiKeyUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyPayload>
        }
        aggregate: {
          args: Prisma.ApiKeyAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateApiKey>
        }
        groupBy: {
          args: Prisma.ApiKeyGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ApiKeyGroupByOutputType>[]
        }
        count: {
          args: Prisma.ApiKeyCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ApiKeyCountAggregateOutputType> | number
        }
      }
    }
    ApiKeyUsage: {
      payload: Prisma.$ApiKeyUsagePayload<ExtArgs>
      fields: Prisma.ApiKeyUsageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ApiKeyUsageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyUsagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ApiKeyUsageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyUsagePayload>
        }
        findFirst: {
          args: Prisma.ApiKeyUsageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyUsagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ApiKeyUsageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyUsagePayload>
        }
        findMany: {
          args: Prisma.ApiKeyUsageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyUsagePayload>[]
        }
        create: {
          args: Prisma.ApiKeyUsageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyUsagePayload>
        }
        createMany: {
          args: Prisma.ApiKeyUsageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ApiKeyUsageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyUsagePayload>[]
        }
        delete: {
          args: Prisma.ApiKeyUsageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyUsagePayload>
        }
        update: {
          args: Prisma.ApiKeyUsageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyUsagePayload>
        }
        deleteMany: {
          args: Prisma.ApiKeyUsageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ApiKeyUsageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ApiKeyUsageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyUsagePayload>[]
        }
        upsert: {
          args: Prisma.ApiKeyUsageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApiKeyUsagePayload>
        }
        aggregate: {
          args: Prisma.ApiKeyUsageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateApiKeyUsage>
        }
        groupBy: {
          args: Prisma.ApiKeyUsageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ApiKeyUsageGroupByOutputType>[]
        }
        count: {
          args: Prisma.ApiKeyUsageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ApiKeyUsageCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UrlScalarFieldEnum = {
  id: 'id',
  originalUrl: 'originalUrl',
  urlHash: 'urlHash',
  shortCode: 'shortCode',
  createdAt: 'createdAt',
  expiresAt: 'expiresAt',
  isActive: 'isActive',
  isFlagged: 'isFlagged',
  flagReason: 'flagReason',
  isPasswordProtected: 'isPasswordProtected',
  passwordHash: 'passwordHash',
  isRotation: 'isRotation',
  rotationType: 'rotationType',
  currentRotation: 'currentRotation',
  lastHealthCheck: 'lastHealthCheck',
  healthStatus: 'healthStatus',
  lastStatusCode: 'lastStatusCode',
  healthCheckError: 'healthCheckError'
} as const

export type UrlScalarFieldEnum = (typeof UrlScalarFieldEnum)[keyof typeof UrlScalarFieldEnum]


export const LinkMetadataScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  title: 'title',
  description: 'description',
  image: 'image',
  logo: 'logo',
  author: 'author',
  publisher: 'publisher',
  date: 'date',
  favicon: 'favicon',
  scrapedAt: 'scrapedAt'
} as const

export type LinkMetadataScalarFieldEnum = (typeof LinkMetadataScalarFieldEnum)[keyof typeof LinkMetadataScalarFieldEnum]


export const RotationLinkScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  destination: 'destination',
  weight: 'weight',
  label: 'label',
  clicks: 'clicks',
  isActive: 'isActive',
  createdAt: 'createdAt'
} as const

export type RotationLinkScalarFieldEnum = (typeof RotationLinkScalarFieldEnum)[keyof typeof RotationLinkScalarFieldEnum]


export const HealthCheckScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  checkedAt: 'checkedAt',
  statusCode: 'statusCode',
  responseTime: 'responseTime',
  status: 'status',
  errorMessage: 'errorMessage'
} as const

export type HealthCheckScalarFieldEnum = (typeof HealthCheckScalarFieldEnum)[keyof typeof HealthCheckScalarFieldEnum]


export const UserUrlScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  urlId: 'urlId',
  createdAt: 'createdAt'
} as const

export type UserUrlScalarFieldEnum = (typeof UserUrlScalarFieldEnum)[keyof typeof UserUrlScalarFieldEnum]


export const AnalyticsScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  clicks: 'clicks',
  lastClick: 'lastClick',
  ipHash: 'ipHash',
  userAgent: 'userAgent',
  referer: 'referer',
  country: 'country'
} as const

export type AnalyticsScalarFieldEnum = (typeof AnalyticsScalarFieldEnum)[keyof typeof AnalyticsScalarFieldEnum]


export const ClickEventScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  clickedAt: 'clickedAt',
  ipHash: 'ipHash',
  userAgent: 'userAgent',
  referer: 'referer',
  country: 'country',
  city: 'city',
  device: 'device',
  browser: 'browser',
  os: 'os',
  utmSource: 'utmSource',
  utmMedium: 'utmMedium',
  utmCampaign: 'utmCampaign'
} as const

export type ClickEventScalarFieldEnum = (typeof ClickEventScalarFieldEnum)[keyof typeof ClickEventScalarFieldEnum]


export const ReportScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  reportedBy: 'reportedBy',
  reason: 'reason',
  createdAt: 'createdAt',
  status: 'status',
  reviewedBy: 'reviewedBy',
  reviewedAt: 'reviewedAt'
} as const

export type ReportScalarFieldEnum = (typeof ReportScalarFieldEnum)[keyof typeof ReportScalarFieldEnum]


export const UrlScanScalarFieldEnum = {
  id: 'id',
  urlId: 'urlId',
  service: 'service',
  result: 'result',
  details: 'details',
  scannedAt: 'scannedAt'
} as const

export type UrlScanScalarFieldEnum = (typeof UrlScanScalarFieldEnum)[keyof typeof UrlScanScalarFieldEnum]


export const RateLimitScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  tokens: 'tokens',
  lastRefill: 'lastRefill'
} as const

export type RateLimitScalarFieldEnum = (typeof RateLimitScalarFieldEnum)[keyof typeof RateLimitScalarFieldEnum]


export const BannedIpScalarFieldEnum = {
  id: 'id',
  ip: 'ip',
  reason: 'reason',
  bannedAt: 'bannedAt',
  bannedBy: 'bannedBy'
} as const

export type BannedIpScalarFieldEnum = (typeof BannedIpScalarFieldEnum)[keyof typeof BannedIpScalarFieldEnum]


export const BannedDomainScalarFieldEnum = {
  id: 'id',
  domain: 'domain',
  reason: 'reason',
  bannedAt: 'bannedAt',
  bannedBy: 'bannedBy'
} as const

export type BannedDomainScalarFieldEnum = (typeof BannedDomainScalarFieldEnum)[keyof typeof BannedDomainScalarFieldEnum]


export const AdminConfigScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value'
} as const

export type AdminConfigScalarFieldEnum = (typeof AdminConfigScalarFieldEnum)[keyof typeof AdminConfigScalarFieldEnum]


export const ApiKeyScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  key: 'key',
  keyPrefix: 'keyPrefix',
  isActive: 'isActive',
  createdAt: 'createdAt',
  lastUsed: 'lastUsed',
  expiresAt: 'expiresAt',
  requestCount: 'requestCount',
  rateLimit: 'rateLimit',
  bypassSecurity: 'bypassSecurity',
  bypassRateLimit: 'bypassRateLimit'
} as const

export type ApiKeyScalarFieldEnum = (typeof ApiKeyScalarFieldEnum)[keyof typeof ApiKeyScalarFieldEnum]


export const ApiKeyUsageScalarFieldEnum = {
  id: 'id',
  apiKeyId: 'apiKeyId',
  endpoint: 'endpoint',
  method: 'method',
  status: 'status',
  timestamp: 'timestamp',
  ipAddress: 'ipAddress'
} as const

export type ApiKeyUsageScalarFieldEnum = (typeof ApiKeyUsageScalarFieldEnum)[keyof typeof ApiKeyUsageScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'HealthStatus'
 */
export type EnumHealthStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'HealthStatus'>
    


/**
 * Reference to a field of type 'HealthStatus[]'
 */
export type ListEnumHealthStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'HealthStatus[]'>
    


/**
 * Reference to a field of type 'ReportStatus'
 */
export type EnumReportStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ReportStatus'>
    


/**
 * Reference to a field of type 'ReportStatus[]'
 */
export type ListEnumReportStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ReportStatus[]'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  url?: Prisma.UrlOmit
  linkMetadata?: Prisma.LinkMetadataOmit
  rotationLink?: Prisma.RotationLinkOmit
  healthCheck?: Prisma.HealthCheckOmit
  userUrl?: Prisma.UserUrlOmit
  analytics?: Prisma.AnalyticsOmit
  clickEvent?: Prisma.ClickEventOmit
  report?: Prisma.ReportOmit
  urlScan?: Prisma.UrlScanOmit
  rateLimit?: Prisma.RateLimitOmit
  bannedIp?: Prisma.BannedIpOmit
  bannedDomain?: Prisma.BannedDomainOmit
  adminConfig?: Prisma.AdminConfigOmit
  apiKey?: Prisma.ApiKeyOmit
  apiKeyUsage?: Prisma.ApiKeyUsageOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

